import { sha256 } from '@noble/hashes/sha256';
import { STAGES, stableCompare } from '@battle/contracts';
import type { BattleMap, BattleState, BattleEvent, Cell, Command, Contact, ContentPack, Frame, Loadout, MatchResult, ObservationState, Point3, PublicState, Roster, Slot, StructureElement, Team, TurnPlan, TurnResolution, UnitState, Validation, WeaponProfile } from '@battle/contracts';
import { absorption, axisSolidDistance, cellPoint, ceilSqrt, distanceCeil, distanceSquared, exactPoint, findPath, generateSolids, getSurface, HEIGHT, hexDistance, integerCubeRoot, integerSqrt, interpolate, lineClear, moveCost, nearestSolidPoint, rat, rayIntersections, surfaceGraph, traceLine } from './geometry';
import type { Solid } from './geometry';
import { TRIG } from './trig';
import { extraCommand, extraAttack, extraDamage, extraContacts, EXTRA_EFFECT_KINDS } from './extra-effects';
import { weaponAfterFire, weaponMoveExtraCost, weaponTick, weaponValidateCommand } from './weapon-actions';
import { bodyCylinderIntersection, compareCollisionTime, rationalTime, timeBounds } from './collision';
import type { CollisionTime } from './collision';
import { impactDescriptor, impactGeometry } from './algebraic';
import type { ExactImpact } from './algebraic';
export * from './geometry';
export * from './collision';
export * from './algebraic';

const clone = <T>(v:T):T => JSON.parse(JSON.stringify(v)) as T;
function cloneCommand(c:Command):Command {return {...c,...(c.path?{path:[...c.path]}:{}),...(c.aim?{aim:{...c.aim}}:{}),...(c.waypoints?{waypoints:c.waypoints.map(p=>({...p}))}:{}),...(c.chosenEffectIds?{chosenEffectIds:[...c.chosenEffectIds]}:{})};}
function cloneUnit(u:UnitState):UnitState {return {...u,stats:immutableObjects.has(u.stats)?u.stats:{...u.stats},loadout:immutableObjects.has(u.loadout)?u.loadout:{main:[...u.loadout.main],sub:[...u.loadout.sub]},skills:immutableObjects.has(u.skills)?u.skills:[...u.skills],rangeOverride:immutableObjects.has(u.rangeOverride)?u.rangeOverride:{...u.rangeOverride},activeCommand:u.activeCommand?cloneCommand(u.activeCommand):null,pendingMove:u.pendingMove?{...u.pendingMove,...(u.pendingMove.via?{via:[...u.pendingMove.via]}:{}),...(u.pendingMove.continuationPath?{continuationPath:[...u.pendingMove.continuationPath]}:{})}:null,effectState:{...u.effectState}};}
function cloneContact(c:Contact):Contact {return {...c,...(c.lastKnown?{lastKnown:{...c.lastKnown}}:{})};}
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const int=(n:unknown,min:number,max:number):n is number=>typeof n==='number'&&Number.isSafeInteger(n)&&n>=min&&n<=max;
const byId=<T extends {id:string}>(a:T,b:T)=>stableCompare(a.id,b.id);
export function canonicalJSON(value:unknown):string {
  if(value===null)return 'null'; if(typeof value==='bigint')return JSON.stringify(String(value));
  if(typeof value==='object'){const previous=immutableObjects.has(value)?encodedCache.get(value):undefined;if(previous)return previous;const result=Array.isArray(value)?'['+(value.every(x=>x&&typeof x==='object'&&'id' in x)?[...value].sort((a,b)=>stableCompare(String(a.id),String(b.id))):value).map(canonicalJSON).join(',')+']':'{'+Object.keys(value as object).sort(stableCompare).filter(k=>(value as Record<string,unknown>)[k]!==undefined).map(k=>JSON.stringify(k)+':'+canonicalJSON((value as Record<string,unknown>)[k])).join(',')+'}';if(immutableObjects.has(value))encodedCache.set(value,result);return result;}
  if(typeof value==='number'&&!Number.isFinite(value))throw new Error('INVALID_SCHEMA: nonfinite');return JSON.stringify(value);
}
const encodedCache=new WeakMap<object,string>();
const utf8Cache=new WeakMap<object,Uint8Array>();
const immutableObjects=new WeakSet<object>();
const knownContent=new Map<string,ContentPack>();
function rememberContent(content:ContentPack,signature:string):void {if(!knownContent.has(signature))knownContent.set(signature,immutable(clone(content)));}
function immutable<T extends object>(value:T):T {if(immutableObjects.has(value))return value;for(const child of Object.values(value))if(child&&typeof child==='object')immutable(child);Object.freeze(value);immutableObjects.add(value);return value;}
export function prepareImmutableState(state:BattleState):BattleState {immutable(state.map);immutable(state.manifest);immutable(state.structures);immutable(state.observations.A.observedCells);immutable(state.observations.B.observedCells);return state;}
const encoder=new TextEncoder();
let wasmHasher:{init():unknown;update(data:Uint8Array):unknown;digest(type:'binary'):Uint8Array}|undefined;
let hashInitialization:Promise<void>|undefined;
/** Optional platform acceleration; canonical bytes and SHA-256 remain identical. */
export function initializeHashing():Promise<void>{hashInitialization??=import('hash-wasm').then(async module=>{wasmHasher=await module.createSHA256();}).catch(()=>{wasmHasher=undefined;});return hashInitialization;}
function cached(value:object):string {if(!immutableObjects.has(value))return canonicalJSON(value);const hit=encodedCache.get(value);if(hit)return hit;const json=canonicalJSON(value);encodedCache.set(value,json);return json;}
export function hashJSON(value:unknown):string {return Array.from(sha256(new TextEncoder().encode(canonicalJSON(value)))).map(v=>v.toString(16).padStart(2,'0')).join('');}
export function stateHash(state:BattleState):string {
  const js=wasmHasher?undefined:sha256.create();if(wasmHasher)wasmHasher.init();const update=(data:Uint8Array)=>wasmHasher?wasmHasher.update(data):js!.update(data),feed=(value:string)=>update(encoder.encode(value)),immutable=(value:object)=>{let encoded=immutableObjects.has(value)?utf8Cache.get(value):undefined;if(!encoded){encoded=encoder.encode(cached(value));if(immutableObjects.has(value))utf8Cache.set(value,encoded);}update(encoded);};
  const observation=(obs:ObservationState)=>{feed('{');Object.keys(obs).sort(stableCompare).forEach((k,index)=>{feed((index?',':'')+JSON.stringify(k)+':');if(k==='observedCells')immutable(obs.observedCells);else feed(canonicalJSON(obs[k as keyof ObservationState]));});feed('}');};
  feed('{');Object.keys(state).sort(stableCompare).forEach((k,index)=>{const value=state[k as keyof BattleState];feed((index?',':'')+JSON.stringify(k)+':');if(k==='observations'){feed('{"A":');observation(state.observations.A);feed(',"B":');observation(state.observations.B);feed('}');}else if(['map','manifest','structures'].includes(k))immutable(value as object);else feed(canonicalJSON(value));});feed('}');return Array.from(wasmHasher?wasmHasher.digest('binary'):js!.digest()).map(v=>v.toString(16).padStart(2,'0')).join('');
}
const SUPPORTED_EFFECTS=new Set(['melee-link','shot-link','suppress-shot','suppress-sniper','quick-shot','instinct-evasion','mobile-sniper','strong-legs','dual-power','blade-parry','close-shooter','escudo-hit','stealth-kill','learn-defense','guaranteed-hit','melee-defense','vital-hit','hearing','sniper-pressure','mixed-dual','precise-sniper','attack-cost','spear-range','twin-snipe','trion-range','pin-sniper','random-power','composite-dual','no-melee-penalty','option-ap','loadout-aptitude','special-power','guard-defense','silencer-hit','distance-power','option-wait','special-random-floor','lead-hit','wire-boost']);
for(const kind of EXTRA_EFFECT_KINDS)SUPPORTED_EFFECTS.add(kind);
const NONE:WeaponProfile={id:'none',name:'空き',family:'none',enabled:true,status:'executable',actionKind:'support',attackAp:null,defenseAp:null,waitUnits:0,basePower:null,baseHit:null,range:null,sector:120,powerModel:'none',requiredSlots:1,dependencies:[],defenseModel:null,penetration:false,structureDamage:null,projectile:false,friendlyFire:false,guardable:false,evadable:false,evidenceStatus:'original',sourceIds:[]};
const weapon=(content:ContentPack,id:string)=>id==='none'?NONE:content.weapons.find(w=>w.id===id);
const effectCache=new WeakMap<ContentPack,{signature:string;entries:WeakMap<string[],ContentPack['effects']>}>();
function effects(unit:UnitState,content:ContentPack):ContentPack['effects'] {const cache=effectCache.get(content)?.entries,canCache=!!cache&&immutableObjects.has(unit.skills),previous=canCache?cache.get(unit.skills):undefined;if(previous)return previous;const result=content.effects.filter(e=>e.enabled&&unit.skills.includes(e.id)).sort((a,b)=>a.priority-b.priority||stableCompare(a.id,b.id));if(canCache)cache.set(unit.skills,result);return result;}
const has=(unit:UnitState,content:ContentPack,kind:string)=>effects(unit,content).some(e=>e.kind===kind);
const selected=(u:UnitState,slot:Slot)=>u[slot];
const familyMatches=(w:WeaponProfile,family:string)=>!family||w.family===family||w.options?.gunClass===family||String(w.options?.compatibleGunClasses??'').split(',').includes(family);
const twinAllowed=(skills:string[],content:ContentPack,main:string,sub:string)=>main===sub&&content.effects.some(e=>e.enabled&&skills.includes(e.id)&&e.kind==='twin-snipe'&&e.values.weapon===main);
function missingDependency(w:WeaponProfile,ids:string[]):boolean{return w.options?.dependenciesMode==='any'?w.dependencies.length>0&&!w.dependencies.some(id=>ids.includes(id)):w.dependencies.some(id=>!ids.includes(id));}
function equipErrors(loadout:Loadout,content:ContentPack):string[] {
  if(!loadout||!Array.isArray(loadout.main)||!Array.isArray(loadout.sub))return ['INVALID_LOADOUT'];
  const result:string[]=[];for(const side of ['main','sub'] as const){if(!Array.isArray(loadout[side])||loadout[side].length!==4||new Set(loadout[side].filter(id=>id!=='none')).size!==loadout[side].filter(id=>id!=='none').length)result.push('LOADOUT_REQUIRES_FOUR_SLOTS');for(const id of loadout[side]??[]){const w=weapon(content,id);if(!w?.enabled)result.push(`UNSUPPORTED_WEAPON:${id}`);else if(missingDependency(w,[...loadout.main,...loadout.sub]))result.push(`MISSING_DEPENDENCY:${id}`);}}return result;
}
export function validateRoster(roster:Roster,stage: keyof typeof STAGES,content:ContentPack):Validation {
  const errors:string[]=[];if(!STAGES[stage]||!roster||!Array.isArray(roster.base)||!Array.isArray(roster.help)||!Array.isArray(roster.changes))return {ok:false,errors:['INVALID_SCHEMA']};
  if(roster.base.length!==4||new Set(roster.base).size!==4)errors.push('FOUR_DISTINCT_BASE_REQUIRED');if(roster.help.length!==STAGES[stage].help)errors.push('HELP_COUNT');
  const identities=[...roster.base,...roster.help].map(id=>content.characters.find(p=>p.id===id)?.characterId??id);if(new Set(identities).size!==identities.length)errors.push('DUPLICATE_CHARACTER');for(const id of roster.base)if(content.characters.find(p=>p.id===id)?.kind==='soldier'||Object.values(content.helpPools).some(pool=>pool.includes(id)))errors.push(`HELP_AS_BASE:${id}`);
  for(const id of [...roster.base,...roster.help]){const p=content.characters.find(p=>p.id===id);if(!p?.enabled){errors.push(`UNSUPPORTED_PRESET:${id}`);continue;}for(const [key,val] of Object.entries(p.stats))if(!int(val,key==='ap'?1:0,100))errors.push(`INVALID_STAT:${id}:${key}`);if(Object.keys(p.stats).length!==7)errors.push(`MISSING_STATS:${id}`);for(const sk of p.skills){const e=content.effects.find(e=>e.id===sk);if(!e?.enabled||!SUPPORTED_EFFECTS.has(e.kind))errors.push(`UNSUPPORTED_EFFECT:${sk}`);}errors.push(...equipErrors(p.defaultLoadout,content));for(const [w,r] of Object.entries(p.rangeOverride))if(!weapon(content,w)||!int(r,0,100))errors.push(`INVALID_RANGE:${w}`);}
  for(const id of roster.help)if(!content.helpPools[stage].includes(id))errors.push(`HELP_NOT_ALLOWED:${id}`);
  const expanded=roster.base.flatMap(id=>Array<string>(STAGES[stage].copies).fill(id)).concat(roster.help),used=new Set<number>();let changed=0;for(const c of roster.changes){if(!int(c.unitIndex,0,STAGES[stage].total-1)||used.has(c.unitIndex))errors.push('INVALID_CHANGE_INDEX');used.add(c.unitIndex);errors.push(...equipErrors(c.loadout,content));const defaults=content.characters.find(p=>p.id===expanded[c.unitIndex])?.defaultLoadout;if(defaults&&canonicalJSON(defaults)!==canonicalJSON(c.loadout))changed++;}if(changed>STAGES[stage].changes)errors.push('CHANGE_LIMIT');return {ok:errors.length===0,errors};
}
function validateRuntimeContent(content:ContentPack):void {const fail=(id:string,field:string):never=>{throw new Error(`INVALID_CONTENT:${id}:${field}`);};for(const kind of ['characters','weapons','effects'] as const){if(!Array.isArray(content[kind]))fail('pack',kind);const ids=content[kind].map(v=>v.id);if(ids.some(id=>typeof id!=='string'||!id)||new Set(ids).size!==ids.length)fail('pack',`${kind}:ids`);}for(const p of content.characters.filter(p=>p.enabled)){if(!p.stats||typeof p.strongLegsIncluded!=='boolean'||!Array.isArray(p.skills)||!p.rangeOverride)fail(p.id,'preset');for(const key of ['ap','trion','attack','defense','evasion','support','technique'] as const)if(!int(p.stats[key],key==='ap'?1:0,100))fail(p.id,key);for(const id of p.skills)if(!content.effects.some(e=>e.id===id&&e.enabled&&SUPPORTED_EFFECTS.has(e.kind)))fail(p.id,`effect:${id}`);const errors=equipErrors(p.defaultLoadout,content);if(errors.length)fail(p.id,errors.join(','));}for(const e of content.effects.filter(e=>e.enabled)){if(!SUPPORTED_EFFECTS.has(e.kind)||!['tick','turn','match','action'].includes(e.duration)||!int(e.priority,0,100)||!int(e.ap,0,100)||!int(e.wait,0,150)||!int(e.maxStacks,1,100)||!e.values)fail(e.id,'effect');}for(const w of content.weapons.filter(w=>w.enabled)){if(!['melee','shot','sniper','blast','support','option'].includes(w.actionKind)||!['attack','trion','fixed','ibis','meteor','none'].includes(w.powerModel)||!int(w.waitUnits,0,30)||!int(w.sector,0,360)||![1,2].includes(w.requiredSlots)||!Array.isArray(w.dependencies))fail(w.id,'profile');for(const key of ['penetration','projectile','friendlyFire','guardable','evadable'] as const)if(typeof w[key]!=='boolean')fail(w.id,key);if(w.defenseModel!==null&&(!['shield','raygust','kogetsu'].includes(w.defenseModel)||!int(w.defenseAp,0,100)))fail(w.id,'defense');if(['melee','shot','sniper','blast'].includes(w.actionKind)){if(!int(w.attackAp,1,100)||!int(w.range,1,100)||!int(w.baseHit,0,100)||w.powerModel==='none'||w.powerModel!=='meteor'&&!int(w.basePower,0,10000)||w.powerModel!=='meteor'&&!int(w.structureDamage,0,10000))fail(w.id,'attack');}else if(w.attackAp!==null||w.powerModel!=='none')fail(w.id,'support');}}
export function compileMatch(map:BattleMap,content:ContentPack,rosters:Record<Team,Roster>,seed:number):BattleState {
  validateRuntimeContent(content);
  if(!int(seed,1,0xffffffff))throw new Error('INVALID_SEED');if(content.ruleVersion!=='R1.3')throw new Error('UNKNOWN_RULE_VERSION');
  for(const team of ['A','B'] as const){const valid=validateRoster(rosters[team],map.stage,content);if(!valid.ok)throw new Error(valid.errors.join(';'));}
  const runtimeMap=clone(map);runtimeMap.cells.sort(byId);runtimeMap.buildings.sort(byId);runtimeMap.spawnSlots.sort((a,b)=>stableCompare(a.team,b.team)||a.index-b.index);const structures=clone(runtimeMap.structures??[]).sort(byId);
  const units:UnitState[]=[];for(const team of ['A','B'] as const){const roster=rosters[team],ids=roster.base.flatMap((id,slot)=>Array.from({length:STAGES[map.stage].copies},(_,copy)=>({id,unitId:`${team}-${String(slot+1).padStart(2,'0')}-${String(copy+1).padStart(2,'0')}`,copy:copy+1}))).concat(roster.help.map((id,index)=>({id,unitId:`${team}-H${String(index+1).padStart(2,'0')}`,copy:1})));
    const spawn=runtimeMap.spawnSlots.filter(s=>s.team===team).sort((a,b)=>a.index-b.index);if(spawn.length<ids.length)throw new Error('MISSING_SPAWNS');ids.forEach((entry,i)=>{const p=content.characters.find(p=>p.id===entry.id)!,stats=clone(p.stats);if(p.skills.some(id=>content.effects.some(e=>e.id===id&&e.kind==='strong-legs'))&&!p.strongLegsIncluded)stats.ap++;const loadout=clone(roster.changes.find(c=>c.unitIndex===i)?.loadout??p.defaultLoadout);let main=loadout.main[0]!,sub=loadout.sub[0]!;if(!twinAllowed(p.skills,content,main,sub)){if(weapon(content,main)?.requiredSlots===2)sub='none';if(weapon(content,sub)?.requiredSlots===2)main='none';}
      units.push({id:entry.unitId,team,presetId:p.id,name:p.name,copy:entry.copy,kind:p.kind,stats,loadout,skills:clone(p.skills),rangeOverride:clone(p.rangeOverride),surfaceId:spawn[i]!.surfaceId,hp:100,ap:stats.ap,alive:true,main,sub,mainDirection:team==='A'?270:90,subDirection:team==='A'?270:90,mainMode:'attack',subMode:'attack',commandIndex:-1,readyAtTick:0,nextAttackAtTick:0,nextCommandAtTick:0,activeCommand:null,commandEndsAtTick:0,pathIndex:0,pendingMove:null,effectState:{position:p.position},supportRemaining:stats.support});});}
  const obs=():ObservationState=>({contacts:[],contactLinks:{},nextContactNumber:1,visibleCells:[],observedCells:clone(runtimeMap.cells),teamGeometryRevision:0});
  const state:BattleState={manifest:{schemaVersion:'battle-1',ruleVersion:content.ruleVersion,contentVersion:content.version,mapVersion:map.version,geometryVersion:map.geometryVersion??'G1',stage:map.stage,seed,hashes:{content:hashJSON(content),map:hashJSON(map)}},map:runtimeMap,turn:1,absoluteTick:0,units:units.sort(byId),projectiles:[],structures,geometryRevision:0,rngState:seed,effects:{movementPolicy:'skip-occupied-v1'},observations:{A:obs(),B:obs()}};
  rememberContent(content,state.manifest.hashes.content!);updateObservations(state,content);return prepareImmutableState(state);
}
function pointFor(state:BattleState,u:UnitState,offset:number):Point3 {const surface=getSurface(state.map,u.surfaceId)!;const cell=surfaceGraph(state.map).cells.get(surface.cellId)!;return cellPoint(cell,surface.z,offset);}
function cellFor(state:BattleState,u:UnitState):Cell {return surfaceGraph(state.map).cells.get(getSurface(state.map,u.surfaceId)!.cellId)!;}
const nearbyCellsCache=new WeakMap<BattleMap,Map<string,Cell[]>>();
function nearbyCells(map:BattleMap,center:Cell,radius:number):Cell[] {let cache=nearbyCellsCache.get(map);if(!cache){cache=new Map();nearbyCellsCache.set(map,cache);}const key=`${center.id}:${radius}`,previous=cache.get(key);if(previous)return previous;const cells:Cell[]=[],graph=surfaceGraph(map);for(let q=-radius;q<=radius;q++)for(let r=Math.max(-radius,-q-radius);r<=Math.min(radius,-q+radius);r++){const cell=graph.cells.get(`c:${center.q+q}:${center.r+r}`);if(cell)cells.push(cell);}cache.set(key,cells);return cells;}
function containingCell(state:BattleState,point:Point3):Cell|undefined {const p=exactPoint(point),r=Number(p.y)/Number(p.d)/3000000,q=(Number(p.x)/Number(p.d)/1732051-r)/2,g=surfaceGraph(state.map);if(Number.isFinite(q)&&Number.isFinite(r))for(let qr=Math.round(q)-2;qr<=Math.round(q)+2;qr++)for(let rr=Math.round(r)-2;rr<=Math.round(r)+2;rr++){const cell=g.cells.get(`c:${qr}:${rr}`);if(cell&&pointInsideCell(p,cell))return cell;}return state.map.cells.find(c=>pointInsideCell(p,c));}
const solidCache=new WeakMap<BattleMap,Solid[]>();
function solidsFor(state:BattleState):Solid[]{let s=solidCache.get(state.map);if(!s){s=generateSolids(state.map,state.structures);solidCache.set(state.map,s);}return s;}
export function inSector(a:{q:number;r:number},b:{q:number;r:number},direction:number,width:number):boolean {
  if(a.q===b.q&&a.r===b.r||width>=360)return true;
  const dx=1732051n*BigInt(2*(b.q-a.q)+b.r-a.r),dy=3000000n*BigInt(b.r-a.r);const [cos,sin]=TRIG[direction*2]!,[c,s]=TRIG[Math.round(width)]!,dot=dx*BigInt(cos)+dy*BigInt(sin),cross=dx*BigInt(sin)-dy*BigInt(cos),abs=cross<0n?-cross:cross;
  if(width<=180)return dot>=0n&&abs*BigInt(c)<=dot*BigInt(s);return dot>=0n||abs*BigInt(-c)>=(-dot)*BigInt(s);
}
const observationCache=new WeakMap<BattleState,{key:string;visible:Record<Team,Set<string>>;visibleLists:Record<Team,string[]>;enemy:Record<Team,Set<string>>}>();
const observationEvents=new WeakMap<BattleState,{team:Team;kind:string;contactId?:string;changedCells?:string[];teamGeometryRevision?:number}[]>();
export function updateObservations(state:BattleState,content?:ContentPack):void {
  content??=knownContent.get(state.manifest.hashes.content!);
  const previous={A:new Map(state.observations.A.contacts.map(c=>[c.contactId,c.channel])),B:new Map(state.observations.B.contacts.map(c=>[c.contactId,c.channel]))};
  const key=state.geometryRevision+'|'+state.units.map(u=>`${u.id}:${u.alive}:${u.surfaceId}:${u.effectState.opticalCloak??false}`).join('|');let cache=observationCache.get(state);const changedGeometry=!cache||cache.key!==key;
  if(changedGeometry){const visible={A:new Set<string>(),B:new Set<string>()},enemy={A:new Set<string>(),B:new Set<string>()},solids=solidsFor(state);
    for(const team of ['A','B'] as const){const allies=state.units.filter(u=>u.alive&&u.team===team);for(const ally of allies){const ac=cellFor(state,ally),as=getSurface(state.map,ally.surfaceId)!,origin=pointFor(state,ally,756000),radius=6+Math.min(3,as.z);for(const cell of nearbyCells(state.map,ac,radius)){if(visible[team].has(cell.id))continue;if(cell.surfaces.some(s=>lineClear(origin,cellPoint(cell,s.z,14000),solids)))visible[team].add(cell.id);}for(const unit of state.units){if(!unit.alive||unit.effectState.opticalCloak||unit.team===team||enemy[team].has(unit.id)||hexDistance(ac,cellFor(state,unit))>radius)continue;if([210000,490000,770000].some(height=>lineClear(origin,pointFor(state,unit,height),solids)))enemy[team].add(unit.id);}}
    }cache={key,visible,visibleLists:{A:immutable([...visible.A].sort(stableCompare)),B:immutable([...visible.B].sort(stableCompare))},enemy};observationCache.set(state,cache);
  }
  for(const team of ['A','B'] as const){extraContacts(state,team,content??({version:state.manifest.contentVersion} as ContentPack));const obs=state.observations[team];obs.visibleCells=cache!.visibleLists[team];if(changedGeometry){const changed:string[]=[],observed=new Map(obs.observedCells.map(c=>[c.id,c]));for(const cell of state.map.cells){if(cache!.visible[team].has(cell.id)&&cached(observed.get(cell.id)!)!==cached(cell)){observed.set(cell.id,clone(cell));changed.push(cell.id);}}if(changed.length){obs.observedCells=[...observed.values()].sort(byId);obs.teamGeometryRevision++;const events=observationEvents.get(state)??[];events.push({team,kind:'TERRAIN_CHANGE',changedCells:changed.sort(stableCompare),teamGeometryRevision:obs.teamGeometryRevision});observationEvents.set(state,events);}}
    for(const unit of state.units.filter(u=>u.team!==team).sort(byId)){const visible=cache!.enemy[team].has(unit.id),hidden=content?[unit.main,unit.sub].some(id=>weapon(content,id)?.options?.stealth===true):['trigger_28','bagworm'].some(id=>unit.main===id||unit.sub===id),radar=unit.alive&&(!hidden||unit.effectState.markTeam===team&&Number(unit.effectState.markUntilTurn??0)>=state.turn||content&&state.units.some(ally=>ally.alive&&ally.team===team&&has(ally,content,'hearing')&&(unit.pendingMove!==null||unit.effectState.lastMovedAt===state.absoluteTick)&&hexDistance(cellFor(state,ally),cellFor(state,unit))<=10));let contact=obs.contacts.find(c=>c.contactId===obs.contactLinks[unit.id]);if(!visible&&!radar){if(contact?.defeated)continue;if(contact&&contact.channel!=='lost'){contact.channel='lost';stripContact(contact);}continue;}if(!contact){const number='E'+String(obs.nextContactNumber++).padStart(2,'0');contact={contactId:`contact-${team}-${number}`,number,reportedCell:cellFor(state,unit).id,observedAtTick:state.absoluteTick,channel:visible?'visual':'radar',tag:''};obs.contacts.push(contact);obs.contactLinks[unit.id]=contact.contactId;}if(contact.channel==='lost'&&!visible){const number='E'+String(obs.nextContactNumber++).padStart(2,'0');contact={contactId:`contact-${team}-${number}`,number,reportedCell:cellFor(state,unit).id,observedAtTick:state.absoluteTick,channel:'radar',tag:''};obs.contacts.push(contact);obs.contactLinks[unit.id]=contact.contactId;}contact.reportedCell=cellFor(state,unit).id;contact.observedAtTick=state.absoluteTick;contact.channel=visible?'visual':'radar';if(visible){Object.assign(contact,{surfaceId:unit.surfaceId,name:unit.name,presetId:unit.presetId,hp:unit.hp,ap:unit.ap,main:unit.main,sub:unit.sub,mainDirection:unit.mainDirection,subDirection:unit.subDirection,mainMode:unit.mainMode??'attack',subMode:unit.subMode??'attack',lastKnown:{name:unit.name,observedAtTick:state.absoluteTick,surfaceId:unit.surfaceId}});}else stripContact(contact);}
  }
  for(const team of ['A','B'] as const){const links=(state.effects[`projectileLinks:${team}`]??{}) as Record<string,string>,reports:NonNullable<PublicState['projectiles']>=[];for(const projectile of state.projectiles){const cell=containingCell(state,projectile.position),visible=projectile.team===team||!!cell&&state.observations[team].visibleCells.includes(cell.id)&&state.units.some(ally=>ally.alive&&ally.team===team&&hexDistance(cellFor(state,ally),cell)<=6+Math.min(3,getSurface(state.map,ally.surfaceId)!.z)&&lineClear(pointFor(state,ally,756000),projectile.position,solidsFor(state)));if(!visible)continue;if(!links[projectile.id]){const next=Number(state.effects[`projectileCounter:${team}`]??0)+1;state.effects[`projectileCounter:${team}`]=next;links[projectile.id]=`projectile-${team}-${String(next).padStart(4,'0')}`;}reports.push({id:links[projectile.id]!,position:clone(projectile.position),radius:projectile.radius,kind:'blast'});}state.effects[`projectileLinks:${team}`]=links;state.effects[`publicProjectiles:${team}`]=reports;}
  const events=observationEvents.get(state)??[];for(const team of ['A','B'] as const)for(const contact of state.observations[team].contacts)if(previous[team].get(contact.contactId)!==contact.channel)events.push({team,kind:contact.channel==='visual'?'VISUAL_DETECT':contact.channel==='radar'?'RADAR_DETECT':'CONTACT_LOST',contactId:contact.contactId});observationEvents.set(state,events);
}
function stripContact(c:Contact):void {delete c.surfaceId;delete c.name;delete c.presetId;delete c.hp;delete c.ap;delete c.main;delete c.sub;delete c.mainDirection;delete c.subDirection;delete c.mainMode;delete c.subMode;delete c.defeated;}
export function projectState(state:BattleState,team:Team):PublicState {
  const obs=state.observations[team],map=publicMapFor(state,obs.observedCells);
  return {stage:state.manifest.stage,turn:state.turn,absoluteTick:state.absoluteTick,team,units:state.units.filter(u=>u.team===team).map(u=>{const own=cloneUnit(u);own.effectState=Object.fromEntries(Object.entries(own.effectState).filter(([key])=>!key.startsWith('link')&&key!=='lastAttackSignature'));return own;}),contacts:[...obs.contacts.map(cloneContact),...extraContacts(state,team,{version:state.manifest.contentVersion} as ContentPack)],map,visibleCells:[...obs.visibleCells],teamGeometryRevision:obs.teamGeometryRevision,counts:{own:state.units.filter(u=>u.team===team&&u.alive).length,enemy:null},result:(state.effects.matchResult as MatchResult|undefined)??null,projectiles:clone((state.effects[`publicProjectiles:${team}`]??[]) as NonNullable<PublicState['projectiles']>)};
}
const publicMapCache=new WeakMap<BattleMap,WeakMap<Cell[],BattleMap>>();
function publicMapFor(state:BattleState,cells:Cell[]):BattleMap {let cache=publicMapCache.get(state.map);if(!cache){cache=new WeakMap();publicMapCache.set(state.map,cache);}const canCache=immutableObjects.has(state.map)&&immutableObjects.has(cells),previous=canCache?cache.get(cells):undefined;if(previous)return previous;const buildings=new Map<string,string[]>();for(const cell of cells)if(cell.buildingId){const ids=buildings.get(cell.buildingId)??[];ids.push(cell.id);buildings.set(cell.buildingId,ids);}const map:BattleMap={schemaVersion:state.map.schemaVersion,id:state.map.id,version:state.map.version,geometryVersion:state.map.geometryVersion,stage:state.map.stage,dimensions:{...state.map.dimensions},renderScale:{...state.map.renderScale},cells,buildings:state.map.buildings.filter(b=>buildings.has(b.id)).map(b=>({...b,cellIds:buildings.get(b.id)!})),spawnSlots:state.map.spawnSlots,landmarks:state.map.landmarks};if(canCache){immutable(map);cache.set(cells,map);}return map;}
export function validatePlan(state:BattleState,plan:TurnPlan,content:ContentPack,team?:Team):Validation {
  const errors:string[]=[];if(!plan||typeof plan.unitId!=='string'||!int(plan.planRevision,0,Number.MAX_SAFE_INTEGER)||!Array.isArray(plan.commands))return {ok:false,errors:['INVALID_SCHEMA']};const unit=state.units.find(u=>u.id===plan.unitId);if(!unit||!unit.alive||team&&unit.team!==team)return {ok:false,errors:['NOT_OWNER_OR_DEAD']};if(plan.commands.length>32)errors.push('COMMAND_LIMIT');const publicMap=projectState(state,unit.team).map;let surface=getSurface(publicMap,unit.surfaceId),main=unit.main,sub=unit.sub;
  const kinds=['MOVE','WAIT','HOLD','TRACK','GUARD','FULL_GUARD','ALL_ROUND','STEALTH','FIRE_AT','SPECIAL'];
  for(const cmd of plan.commands){if(!cmd||!kinds.includes(cmd.kind)){errors.push('INVALID_SCHEMA');continue;}for(const key of ['mainDirection','subDirection'] as const)if(cmd[key]!==undefined&&!int(cmd[key],0,359))errors.push('INVALID_DIRECTION');for(const side of ['main','sub'] as const){const mode=cmd[side+'Mode' as 'mainMode'|'subMode'];if(mode!==undefined&&!['attack','shield'].includes(mode))errors.push('INVALID_MODE');}if(cmd.durationTicks!==undefined&&(!int(cmd.durationTicks,5,150)||cmd.durationTicks%5))errors.push('INVALID_DURATION');main=cmd.main??main;sub=cmd.sub??sub;const mw=weapon(content,main);if(mw?.requiredSlots===2&&cmd.sub===undefined&&!twinAllowed(unit.skills,content,main,sub))sub='none';const sw=weapon(content,sub);if(sw?.requiredSlots===2&&cmd.main===undefined&&sw.actionKind!=='option'&&!twinAllowed(unit.skills,content,main,sub))main='none';if(main!=='none'&&!unit.loadout.main.includes(main)||sub!=='none'&&!unit.loadout.sub.includes(sub)||!mw?.enabled||!sw?.enabled)errors.push('ILLEGAL_EQUIPMENT');if(!twinAllowed(unit.skills,content,main,sub)&&(mw?.requiredSlots===2&&sub!=='none'||sw?.requiredSlots===2&&main!=='none'&&sw.actionKind!=='option'))errors.push('TWO_HAND_DEPENDENCY');for(const w of [mw,sw])if(w&&missingDependency(w,[main,sub]))errors.push('ACTIVE_DEPENDENCY');
    for(const side of ['main','sub'] as const)if(cmd[side+'Mode' as 'mainMode'|'subMode']==='shield'&&!weapon(content,side==='main'?main:sub)?.options?.supportsShieldMode)errors.push('INVALID_SHIELD_MODE');if(cmd.kind==='MOVE'){if(!Array.isArray(cmd.path)||!cmd.path.length){errors.push('EMPTY_PATH');continue;}for(const id of cmd.path){const next=getSurface(publicMap,id);if(!next||!surface||hexDistance(surfaceGraph(publicMap).cells.get(next.cellId)!,surfaceGraph(publicMap).cells.get(surface.cellId)!)!==1||moveCost(surface,next,!!(mw?.options?.grasshopper||sw?.options?.grasshopper))===null)errors.push('INVALID_PATH');surface=next;}}
    if(cmd.kind==='TRACK'&&!state.observations[unit.team].contacts.some(c=>c.contactId===cmd.contactId))errors.push('UNKNOWN_CONTACT');if(cmd.kind==='GUARD'&&(!state.units.some(u=>u.id===cmd.allyId&&u.team===unit.team&&u.alive)||cmd.allyId===unit.id))errors.push('INVALID_ALLY');
    if(cmd.kind==='FULL_GUARD'&&(!mw?.defenseModel||!sw?.defenseModel))errors.push('FULL_GUARD_REQUIRES_TWO');if(cmd.kind==='ALL_ROUND'&&!([mw,sw].some(w=>w?.defenseModel==='shield')))errors.push('ALL_ROUND_REQUIRES_SHIELD');if(cmd.kind==='STEALTH'&&!([mw,sw].some(w=>w?.options?.stealth)))errors.push('STEALTH_REQUIRES_BAGWORM');
    if(cmd.kind==='SPECIAL'){const effect=content.effects.find(e=>e.id===cmd.effectId&&e.enabled&&unit.skills.includes(e.id)),option=weapon(content,cmd.weaponId??cmd.effectId??'');if(!((effect&&(effect.triggerHook==='COMMAND_START'||EXTRA_EFFECT_KINDS.includes(effect.kind))&&SUPPORTED_EFFECTS.has(effect.kind))||(option?.enabled&&option.options?.specialAction&&[main,sub].includes(option.id))))errors.push('UNSUPPORTED_SPECIAL');errors.push(...weaponValidateCommand(state,{...unit,main,sub},cmd,content));}
    if(cmd.kind==='FIRE_AT'){const w=cmd.slot==='sub'?sw:mw;if(!w||w.attackAp===null||w.range===null)errors.push('FIRE_PROFILE');if(!validPoint(cmd.aim))errors.push('INVALID_AIM');else {const p=exactPoint(cmd.aim),known=state.observations[unit.team].visibleCells.some(id=>pointInsideCell(p,surfaceGraph(publicMap).cells.get(id)!))||state.observations[unit.team].observedCells.some(c=>pointInsideCell(p,c)&&c.surfaces.some(s=>p.z===BigInt(s.z)*HEIGHT*p.d));if(!known)errors.push('UNKNOWN_AIM');}for(const k of ['chargeBp','blastBp'] as const)if(cmd[k]!==undefined&&!int(cmd[k],1,10000))errors.push('INVALID_BASIS_POINT');if(cmd.divisionCount!==undefined&&!int(cmd.divisionCount,1,64))errors.push('INVALID_DIVISION');}
  }return {ok:errors.length===0,errors};
}
function validPoint(p:Point3|undefined):p is Point3{return !!p&&[p.x,p.y,p.z].every(s=>typeof s==='string'&&/^-?(0|[1-9]\d*)$/.test(s))&&(p.denominator===undefined||/^[1-9]\d*$/.test(p.denominator));}
function pointInsideCell(p:ReturnType<typeof exactPoint>,cell:Cell):boolean {const x=1732051n*BigInt(2*cell.q+cell.r),y=3000000n*BigInt(cell.r),dx=p.x-x*p.d,dy=p.y-y*p.d;return (dx<0n?-dx:dx)<=1732051n*p.d&&1000000n*(dx<0n?-dx:dx)+1732051n*(dy<0n?-dy:dy)<=3464102000000n*p.d;}

type Intent={id:string;actor:UnitState;slot:Slot;profile:WeaponProfile;target?:UnitState;aim:Point3;group:number;cost:number;followup?:boolean;lead?:boolean;powerBp:number;guaranteedHit?:boolean;waypoints?:Point3[]};
type Blast={id:string;actorId:string;profile:WeaponProfile;origin:Point3;budget:number;radius:bigint;exactImpact?:ExactImpact};
type Context={state:BattleState;content:ContentPack;tick:number;events:BattleEvent[];serial:number;plans:Map<string,TurnPlan>};
const eventDisclosure=new WeakMap<BattleEvent,Record<Team,{actorId?:string;targetId?:string}>>();
function emit(ctx:Context,kind:string,actorId?:string,targetId?:string,details:Partial<BattleEvent>={}):void {
  const actor=ctx.state.units.find(u=>u.id===actorId),event:BattleEvent={id:`${ctx.state.turn}:${ctx.tick}:${String(ctx.serial++).padStart(5,'0')}`,turn:ctx.state.turn,tick:ctx.tick,groupId:`${ctx.tick}:state`,kind,actorId,targetId,reasonCode:kind,description:kind,planRevision:actor?ctx.plans.get(actor.id)?.planRevision:undefined,commandIndex:actor?.commandIndex,...details};ctx.events.push(event);const disclosed={} as Record<Team,{actorId?:string;targetId?:string}>;for(const team of ['A','B'] as const){const obs=ctx.state.observations[team],convert=(id:string|undefined)=>id===undefined?undefined:ctx.state.units.some(u=>u.id===id&&u.team===team)?id:obs.contacts.some(c=>c.channel==='visual'&&c.contactId===obs.contactLinks[id])?obs.contactLinks[id]:undefined;disclosed[team]={actorId:convert(event.actorId),targetId:convert(event.targetId)};}eventDisclosure.set(event,disclosed);
}
function roll(ctx:Context,actor:UnitState,target:UnitState,purpose:string,percent:number,group:number,slot:Slot):boolean {
  let x=ctx.state.rngState;x=(x^(x<<13))>>>0;x=(x^(x>>>17))>>>0;x=(x^(x<<5))>>>0;ctx.state.rngState=x;
  emit(ctx,'RANDOM',actor.id,target.id,{groupId:`${ctx.tick}:${group}`,slot,random:{purpose,value:x,percent}});return x%100<percent;
}
function pay(ctx:Context,u:UnitState,cost:number,kind:string,wait=0,group='state',slot?:Slot,targetId?:string,visual?:Record<string,unknown>):void {const before=u.ap,ready=u.readyAtTick;u.ap-=cost;if(wait)u.readyAtTick=Math.max(u.readyAtTick,ctx.tick)+wait;emit(ctx,kind,u.id,targetId,{apBefore:before,apAfter:u.ap,waitBefore:ready,waitAfter:u.readyAtTick,groupId:`${ctx.tick}:${group}`,slot,...(visual?{details:{visual}}:{})});}
function attackCost(u:UnitState,w:WeaponProfile,content:ContentPack):number {
  let cost=w.attackAp??0;if(w.actionKind==='sniper'&&has(u,content,'mobile-sniper'))cost--;
  if(w.actionKind==='melee'&&['SN','GU','SH'].includes(String(u.effectState.position))&&!has(u,content,'no-melee-penalty'))cost+=Number(w.options?.nonAttackerPenaltyAp??0);
  for(const e of effects(u,content)){const family=String(e.values.family??''),match=familyMatches(w,family);if(e.kind==='attack-cost'&&match)cost+=Number(e.values.amount??0);}
  return Math.max(1,cost);
}
function rangeFor(u:UnitState,w:WeaponProfile,content:ContentPack):number {const original=weapon(content,w.id);let range=!original||w.range!==original.range?w.range??0:u.rangeOverride[w.id]??w.range??0;if(w.options?.noRangeBonus)return range;for(const e of effects(u,content)){if(e.kind==='trion-range'&&['shot','blast'].includes(w.actionKind))range+=Number(e.values.range??0);if(e.kind==='precise-sniper'&&w.actionKind==='sniper')range+=Number(e.values.range??0);if(e.kind==='spear-range'&&w.family===e.values.family)range=Number(e.values.range??range);}return range;}
function canAim(state:BattleState,u:UnitState,w:WeaponProfile,target:UnitState|undefined,aim:Point3,slot:Slot,content:ContentPack,waypoints?:Point3[]):boolean {
  if(!u.alive||w.attackAp===null||w.range===null||w.options?.stealth)return false;const ac=cellFor(state,u),tc=target?cellFor(state,target):state.map.cells.find(c=>pointInsideCell(exactPoint(aim),c));if(!tc||hexDistance(ac,tc)>rangeFor(u,w,content)||!inSector(ac,tc,u[slot+'Direction' as 'mainDirection'|'subDirection'],w.sector))return false;
  if(target&&target.effectState.opticalCloak)return false;if(target&&!state.observations[u.team].contacts.some(c=>c.channel==='visual'&&c.contactId===state.observations[u.team].contactLinks[target.id]))return false;
  if(waypoints?.length){let from=pointFor(state,u,560000);for(const to of [...waypoints,aim]){if(!validPoint(to))return false;const cell=state.map.cells.find(c=>pointInsideCell(exactPoint(to),c));if(!cell||hexDistance(ac,cell)>rangeFor(u,w,content)||!traceLine(from,to,solidsFor(state)).clear)return false;from=to;}return true;}
  if(w.powerModel==='meteor')return u.stats.trion>0;
  const origin=pointFor(state,u,560000),hits=rayIntersections(origin,aim,solidsFor(state));if(!w.penetration)return !hits.length||!target;
  let budget=Number(w.options?.penetrationBudget??12)*u.stats.trion*u.stats.trion;for(const hit of hits){budget-=absorption(hit,origin,aim);if(budget<=0)return !target;}return true;
}
function buildIntents(ctx:Context):Intent[] {
  const visible={A:new Set(ctx.state.observations.A.contacts.filter(c=>c.channel==='visual').map(c=>c.contactId)),B:new Set(ctx.state.observations.B.contacts.filter(c=>c.channel==='visual').map(c=>c.contactId))},result:Intent[]=[];for(const u of ctx.state.units){if(!u.alive||u.ap===0||ctx.tick<u.readyAtTick||ctx.tick<u.nextAttackAtTick)continue;const cmd=u.activeCommand;if(cmd&&['FULL_GUARD','ALL_ROUND','STEALTH'].includes(cmd.kind))continue;
    for(const slot of ['main','sub'] as const){const w=weapon(ctx.content,selected(u,slot));if(!w?.enabled||w.attackAp===null||u[slot+'Mode' as 'mainMode'|'subMode']==='shield'||slot==='sub'&&(w.requiredSlots===2&&!twinAllowed(u.skills,ctx.content,u.main,u.sub)||u.effectState.synthesisReady||u.effectState.leadReady||u.effectState.leadWeaponReady==='trigger_38'))continue;let target:UnitState|undefined,aim:Point3;
      if(cmd?.kind==='FIRE_AT'&&(cmd.slot??'main')===slot){if(u.effectState.firedCommand===u.commandIndex||!cmd.aim)continue;aim=cmd.aim;}
      else {if(cmd?.kind==='FIRE_AT'&&(cmd.slot??'main')===slot)continue;const tracked=cmd?.contactId?Object.entries(ctx.state.observations[u.team].contactLinks).find(([,contact])=>contact===cmd.contactId)?.[0]:undefined;const candidates=ctx.state.units.filter(t=>t.alive&&t.team!==u.team&&!t.effectState.opticalCloak&&visible[u.team].has(ctx.state.observations[u.team].contactLinks[t.id]??'')).sort((a,b)=>(a.id===tracked?-1:b.id===tracked?1:0)||hexDistance(cellFor(ctx.state,u),cellFor(ctx.state,a))-hexDistance(cellFor(ctx.state,u),cellFor(ctx.state,b))||stableCompare(a.id,b.id));target=candidates.find(t=>{const mods=extraAttack(ctx.state,u,t,w,ctx.content,ctx.tick);return canAim(ctx.state,u,mods.synthetic??w,t,pointFor(ctx.state,t,490000),slot,ctx.content,mods.aimWaypoints);});if(!target)continue;aim=pointFor(ctx.state,target,490000);}
      const mods=extraAttack(ctx.state,u,target,w,ctx.content,ctx.tick);let profile=mods.synthetic??w;
      if(slot==='sub'&&has(u,ctx.content,'composite-dual')&&[u.main,u.sub].every(id=>weapon(ctx.content,id)?.actionKind==='shot'))profile={...profile,actionKind:'sniper',waitUnits:profile.waitUnits+1};
      if(!canAim(ctx.state,u,profile,target,aim,slot,ctx.content,mods.aimWaypoints))continue;
      result.push({id:`${ctx.tick}:${u.id}:${slot}`,actor:u,slot,profile,target,aim,group:1,cost:attackCost(u,profile,ctx.content),powerBp:mods.powerBp??10000,lead:mods.lead,guaranteedHit:mods.guaranteedHit,waypoints:mods.aimWaypoints});
    }
  }
  for(const intent of result)if(has(intent.actor,ctx.content,'quick-shot')&&result.some(other=>other.target?.id===intent.actor.id))intent.group=0;
  return result.sort((a,b)=>a.group-b.group||stableCompare(a.actor.id,b.actor.id)||stableCompare(a.slot,b.slot)||stableCompare(a.target?.id??'',b.target?.id??''));
}
export function meteorParameters(trion:number,chargeBp=10000,blastBp=10000,divisionCount=1,budgetCoefficient=12):{budget:number;power:number;radius:bigint} {
  if(!int(trion,0,100)||!int(chargeBp,1,10000)||!int(blastBp,1,10000)||!int(divisionCount,1,64)||!int(budgetCoefficient,1,1000))throw new Error('INVALID_METEOR_OPTIONS');const e=BigInt(budgetCoefficient)*BigInt(trion)*BigInt(trion)*BigInt(chargeBp)*BigInt(blastBp)/(10000n*10000n*BigInt(divisionCount));if(e===0n)throw new Error('ZERO_METEOR_BUDGET');return {budget:Number(e),power:Number(e/6n),radius:integerCubeRoot(e*1000000n**3n/6n)};
}
function fireProjectile(ctx:Context,intent:Intent):void {
  const cmd=intent.actor.activeCommand,parameters=meteorParameters(intent.actor.stats.trion,cmd?.chargeBp,cmd?.blastBp,cmd?.divisionCount,Number(intent.profile.options?.blastBudget??12)),origin=pointFor(ctx.state,intent.actor,560000),waypoints=intent.waypoints?.length?[...intent.waypoints,intent.aim].filter((p,i,a)=>i===0||canonicalJSON(p)!==canonicalJSON(a[i-1])):undefined,aim=waypoints?.[0]??intent.aim,length=distanceCeil(origin,aim),count=cmd?.divisionCount??1;
  for(const e of effects(intent.actor,ctx.content))if(e.kind==='trion-range')parameters.radius+=3464102n*BigInt(Number(e.values.blastRange??0));
  for(let i=0;i<count;i++)ctx.state.projectiles.push({id:`p:${ctx.state.turn}:${ctx.tick}:${intent.actor.id}:${intent.slot}:${String(i).padStart(2,'0')}`,ownerId:intent.actor.id,team:intent.actor.team,profileId:intent.profile.id,profile:clone(intent.profile),origin,aim,waypoints,waypointIndex:0,position:origin,travelledDistance:'0',speed:String(intent.profile.options?.projectileSpeed??1732051),length:String(length||1n),ageTicks:0,bornAtTick:ctx.state.absoluteTick,budget:parameters.budget,radius:String(parameters.radius),hp:1,fuse:Number(intent.profile.options?.fuse??0)});
  emit(ctx,'PROJECTILE_FIRE',intent.actor.id,intent.target?.id,{groupId:`${ctx.tick}:${intent.group}`,slot:intent.slot,details:{origin,aim:intent.aim,budget:parameters.budget,radius:String(parameters.radius),divisionCount:count}});
}
function powerFor(ctx:Context,intent:Intent):number {
  const u=intent.actor,w=intent.profile;const power=w.powerModel==='attack'?(w.basePower??0)*u.stats.attack:w.powerModel==='trion'?(w.basePower??0)*u.stats.trion:w.powerModel==='ibis'?20*u.stats.trion:w.powerModel==='fixed'?w.basePower??0:0;let bp=intent.powerBp,add=0;const distance=intent.target?hexDistance(cellFor(ctx.state,u),cellFor(ctx.state,intent.target)):0;
  for(const e of effects(u,ctx.content)){const family=String(e.values.family??''),match=familyMatches(w,family);
    if(e.kind==='close-shooter'&&w.actionKind==='shot'&&distance<=Number(e.values.maxRange))bp=Math.floor(bp*Number(e.values.powerBp)/10000);
    if(e.kind==='dual-power'&&match&&[u.main,u.sub].every(id=>{const p=weapon(ctx.content,id);return p?.attackAp!==null&&(p?.family===family||p?.options?.gunClass===family);}))bp=Math.floor(bp*Number(e.values.bp)/10000);
    if(e.kind==='pin-sniper'&&w.actionKind==='sniper'&&intent.target&&(['WAIT','HOLD'].includes(intent.target.activeCommand?.kind??'')||ctx.events.some(ev=>ev.kind==='FIRE'&&ev.actorId===intent.target!.id&&ev.tick===ctx.tick)))bp=Math.floor(bp*Number(e.values.bp)/10000);
    if(e.kind==='distance-power'&&match&&distance<=Number(e.values.maxRange))bp+=Number(e.values.bpPerCell)*(Number(e.values.maxRange)-distance);
    if(e.kind==='mixed-dual'&&weapon(ctx.content,u.main)?.actionKind!==weapon(ctx.content,u.sub)?.actionKind)bp=Math.floor(bp*Number(e.values.bp)/10000);
    if(e.kind==='composite-dual'&&intent.slot==='sub'&&w.actionKind===e.values.subActionKind)bp=Math.floor(bp*Number(e.values.subPowerBp)/10000);
    if(e.kind==='wire-boost'&&u.effectState.wire)bp=Math.floor(bp*Number(e.values.powerBp)/10000);
    if(e.kind==='random-power'&&w.actionKind===e.values.actionKind){let x=ctx.state.rngState;x=(x^(x<<13))>>>0;x=(x^(x>>>17))>>>0;x=(x^(x<<5))>>>0;ctx.state.rngState=x;const min=Number(e.values.minBp),max=Number(e.values.maxBp),random=min+x%(max-min+1);emit(ctx,'RANDOM_POWER',u.id,intent.target?.id,{details:{effectId:e.id,value:x,bp:random},groupId:`${ctx.tick}:${intent.group}`});bp=Math.floor(bp*random/10000);}
    if(e.kind==='special-power'&&u.effectState.special===e.values.special)bp=Math.floor(bp*Number(e.values.bp)/10000);
    if(e.kind==='loadout-aptitude'&&match)bp=Math.floor(bp*Number(e.values.bp??10000)/10000);
  }add+=Number(u.effectState.powerAdd??0);return Math.floor((power+add)*bp/10000);
}
function defense(ctx:Context,target:UnitState,attacker:UnitState|undefined,origin:Point3,w:WeaponProfile,group:number):{reduction:number;guarded:boolean} {
  const tc=cellFor(ctx.state,target),oc=attacker?cellFor(ctx.state,attacker):ctx.state.map.cells.find(c=>pointInsideCell(exactPoint(origin),c))??tc;
  const legal: {slot:Slot;w:WeaponProfile;reduction:number;cost:number}[]=[];for(const slot of ['main','sub'] as const){const p=weapon(ctx.content,selected(target,slot));if(!p?.defenseModel||p.defenseAp===null||p.defenseModel==='raygust'&&target[slot+'Mode' as 'mainMode'|'subMode']!=='shield'||p.defenseModel==='kogetsu'&&w.actionKind!=='melee'||p.requiredSlots===2&&slot==='sub')continue;const all=target.activeCommand?.kind==='ALL_ROUND'&&p.defenseModel==='shield';if(!all&&!inSector(tc,oc,target[slot+'Direction' as 'mainDirection'|'subDirection'],p.sector))continue;let reduction=p.defenseModel==='shield'?4*target.stats.trion+2*target.stats.defense:p.defenseModel==='raygust'?6*target.stats.defense+target.stats.trion:4*target.stats.defense;if(all)reduction=Math.floor(reduction/2);
    for(const e of effects(target,ctx.content)){if(e.kind==='blade-parry'&&p.defenseModel==='kogetsu')reduction=Math.floor(reduction*Number(e.values.bp)/10000);if(e.kind==='guard-defense'&&target.activeCommand?.kind==='GUARD')reduction=Math.floor(reduction*Number(e.values.bp)/10000);if(e.kind==='learn-defense'&&target.effectState.lastAttackSignature===`${attacker?.id}:${w.id}`&&Number(target.effectState.sameAttackCount??0)>=Number(e.values.repeat)-1)reduction=Math.floor(reduction*Number(e.values.bp)/10000);if(e.kind==='wire-boost'&&target.effectState.wire)reduction=Math.floor(reduction*Number(e.values.defenseBp)/10000);}
    legal.push({slot,w:p,reduction,cost:p.defenseAp});}
  let chosen=legal.sort((a,b)=>b.reduction-a.reduction||(a.slot==='main'?-1:1)).filter(p=>p.cost<=target.ap).slice(0,1);if(target.activeCommand?.kind==='FULL_GUARD'&&legal.length===2&&legal.reduce((n,p)=>n+p.cost,0)<=target.ap)chosen=legal;
  if(w.actionKind==='melee'&&has(target,ctx.content,'melee-defense')&&target.ap>=1&&[...target.loadout.main,...target.loadout.sub].some(id=>weapon(ctx.content,id)?.actionKind==='melee')&&[target.mainDirection,target.subDirection].some(direction=>inSector(tc,oc,direction,120))){const blade={slot:'main' as const,w:{...NONE,defenseModel:'kogetsu' as const,defenseAp:1,waitUnits:1},reduction:4*target.stats.defense,cost:1};if(!chosen.length||chosen.reduce((n,p)=>n+p.reduction,0)<blade.reduction)chosen=[blade];}
  if(!chosen.length)return {reduction:0,guarded:false};const cost=chosen.reduce((n,p)=>n+p.cost,0),wait=Math.max(...chosen.map(p=>p.w.defenseModel==='kogetsu'&&has(target,ctx.content,'blade-parry')?0:p.w.waitUnits*5));pay(ctx,target,cost,'DEFEND',wait,String(group),chosen[0]!.slot);let reduction=chosen.reduce((n,p)=>n+p.reduction,0);
  if(attacker){const suppress=effects(attacker,ctx.content).filter(e=>e.kind==='suppress-shot'&&w.actionKind==='shot'||e.kind==='suppress-sniper'&&w.actionKind==='sniper');for(const _e of suppress)pay(ctx,target,Math.min(target.ap,1),'SUPPRESS',5,String(group));}
  if(target.effectState.defenseBp)reduction=Math.floor(reduction*Number(target.effectState.defenseBp)/10000);if(Number(target.effectState.decoyActions??0)>0)reduction=Math.floor(reduction*Number(target.effectState.decoyDefenseBp??10000)/10000);return {reduction,guarded:true};
}
function redirectGuard(ctx:Context,intent:Intent,target:UnitState):UnitState {
  if(!intent.profile.guardable)return target;const g=ctx.state.units.filter(u=>u.alive&&u.team===target.team&&u.id!==target.id&&u.activeCommand?.kind==='GUARD'&&u.activeCommand.allyId===target.id&&hexDistance(cellFor(ctx.state,u),cellFor(ctx.state,target))<=1&&traceLine(pointFor(ctx.state,u,560000),pointFor(ctx.state,target,490000),solidsFor(ctx.state)).clear&&[u.main,u.sub].some((id,i)=>{const w=weapon(ctx.content,id);return w?.defenseModel&&w.defenseAp!==null&&w.defenseAp<=u.ap&&inSector(cellFor(ctx.state,u),cellFor(ctx.state,intent.actor),i?u.subDirection:u.mainDirection,w.sector);})).sort((a,b)=>b.stats.support-a.stats.support||hexDistance(cellFor(ctx.state,a),cellFor(ctx.state,target))-hexDistance(cellFor(ctx.state,b),cellFor(ctx.state,target))||stableCompare(a.id,b.id));if(g.length)emit(ctx,'GUARD_REDIRECT',g[0]!.id,target.id,{groupId:`${ctx.tick}:${intent.group}`});return g[0]??target;
}
function applyUnitHit(ctx:Context,intent:Intent,power:number,damages:Map<string,number>,instant:Set<string>):void {
  let target=intent.target;if(!target)return;const original=target;target=redirectGuard(ctx,intent,target);const actor=intent.actor,w=intent.profile,ownerEffects=effects(actor,ctx.content),defEffects=effects(target,ctx.content),instinct=has(target,ctx.content,'instinct-evasion');
  let hit=clamp((w.baseHit??100)+2*(actor.stats.technique-6),5,100);for(const e of ownerEffects){if(e.kind==='precise-sniper'&&w.actionKind==='sniper'||e.kind==='pin-sniper'&&w.actionKind==='sniper'&&(['WAIT','HOLD'].includes(target.activeCommand?.kind??'')||ctx.events.some(ev=>ev.kind==='FIRE'&&ev.actorId===target!.id&&ev.tick===ctx.tick))||e.kind==='silencer-hit'&&[actor.main,actor.sub].some(id=>weapon(ctx.content,id)?.options?.silencer)||e.kind==='close-shooter'&&w.actionKind==='shot'&&hexDistance(cellFor(ctx.state,actor),cellFor(ctx.state,target))<=Number(e.values.maxRange))hit=clamp(hit+Number(e.values.hit??0),5,100);}
  const guaranteed=intent.guaranteedHit||ownerEffects.some(e=>e.kind==='guaranteed-hit'&&e.values.weapon===w.id&&!instinct);if(intent.lead)for(const e of ownerEffects.filter(e=>e.kind==='lead-hit'))hit=clamp(hit+Number(e.values.hit??0),5,100);if(!guaranteed&&!roll(ctx,actor,target,'hit',hit,intent.group,intent.slot)){emit(ctx,'MISS',actor.id,target.id,{groupId:`${ctx.tick}:${intent.group}`,slot:intent.slot});return;}
  if(w.actionKind==='sniper'&&has(actor,ctx.content,'sniper-pressure'))pay(ctx,target,Math.min(1,target.ap),'SNIPER_PRESSURE',0,String(intent.group));const sector=[target.mainDirection,target.subDirection].some(d=>inSector(cellFor(ctx.state,target!),cellFor(ctx.state,actor),d,120));let evade=sector||instinct?clamp(3*target.stats.evasion,0,60):0;if(instinct&&w.actionKind==='sniper')evade=clamp(evade+20,0,80);for(const e of defEffects)if(e.kind==='wire-boost'&&target.effectState.wire||e.kind==='option-ap'&&[target.main,target.sub].includes(String(e.values.weapon)))evade=clamp(evade+Number(e.values.evade??0),0,80);if(target.effectState.lead||Number(target.effectState.idatenCornerUntil??0)>ctx.state.absoluteTick)evade=0;
  if(ownerEffects.some(e=>e.kind==='stealth-kill')&&[actor.main,actor.sub].some(id=>weapon(ctx.content,id)?.options?.silencer)&&!sector&&!instinct)evade=0;if(w.evadable&&evade>0&&roll(ctx,actor,target,'evade',evade,intent.group,intent.slot)){emit(ctx,'EVADE',target.id,actor.id,{groupId:`${ctx.tick}:${intent.group}`,slot:intent.slot});return;}
  const guard=defense(ctx,target,actor,pointFor(ctx.state,actor,560000),w,intent.group),damage=Math.max(0,power-guard.reduction);damages.set(target.id,(damages.get(target.id)??0)+damage);const signature=`${actor.id}:${w.id}`;target.effectState.sameAttackCount=target.effectState.lastAttackSignature===signature?Number(target.effectState.sameAttackCount??0)+1:1;target.effectState.lastAttackSignature=signature;extraDamage(ctx.state,target,{lead:intent.lead},ctx.content,ctx.tick);
  if(ownerEffects.some(e=>e.kind==='stealth-kill')&&[actor.main,actor.sub].some(id=>weapon(ctx.content,id)?.options?.silencer)&&!sector&&!instinct||ownerEffects.some(e=>e.kind==='vital-hit'&&roll(ctx,actor,target,'vital',Number(e.values.percent),intent.group,intent.slot)))instant.add(target.id);

  emit(ctx,'DAMAGE',actor.id,target.id,{groupId:`${ctx.tick}:${intent.group}`,slot:intent.slot,power,reduction:guard.reduction,damage,details:{originalTargetId:original.id,defenseOrder:'attackerId-slot-effectId'}});
}
function addStructure(damage:Map<string,number>,id:string,amount:number):void {if(amount>0)damage.set(id,(damage.get(id)??0)+amount);}
function ibis(ctx:Context,intent:Intent,damage:Map<string,number>):number {
  const contribution=new Map<string,number>();
  const origin=pointFor(ctx.state,intent.actor,560000),aimCell=containingCell(ctx.state,intent.aim),horizontal=aimCell?hexDistance(cellFor(ctx.state,intent.actor),aimCell):0,range=rangeFor(intent.actor,intent.profile,ctx.content),endpoint=interpolate(origin,intent.aim,horizontal?rat(BigInt(range),BigInt(horizontal)):rat(BigInt(range)*HEIGHT,distanceCeil(origin,intent.aim)||1n)),budget=Number(intent.profile.options?.penetrationBudget??12)*intent.actor.stats.trion**2;
  let firstUnit:UnitState|undefined,firstTime:CollisionTime|undefined;for(const unit of ctx.state.units){if(!unit.alive||unit.id===intent.actor.id)continue;const hit=bodyCylinderIntersection(origin,endpoint,pointFor(ctx.state,unit,0));if(hit&&(!firstTime||compareCollisionTime(hit.enter,firstTime)<0||compareCollisionTime(hit.enter,firstTime)===0&&stableCompare(unit.id,firstUnit!.id)<0)){firstTime=hit.enter;firstUnit=unit;}}
  const beamEnd=firstTime?interpolate(origin,endpoint,timeBounds(firstTime,256).upper):endpoint;let remaining=budget,stop=beamEnd;
  const exact=firstTime?impactDescriptor(origin,endpoint,firstTime):undefined;
  if(exact){const {geometry:g,point:exactEnd}=impactGeometry(exact),start=g.point(origin);let exactStop=exactEnd;remaining=budget;contribution.clear();for(const hit of g.intersections(start,exactEnd,solidsFor(ctx.state))){const absorb=g.absorption(hit,start,exactEnd);addStructure(contribution,hit.solid.id,Math.min(remaining,absorb));if(remaining<=absorb){remaining=0;exactStop=hit.point;break;}remaining-=absorb;}
    const radius=BigInt(Number(intent.profile.options?.localFractureCoefficient??500000))*BigInt(intent.actor.stats.trion)/6n,delta=g.subtract(exactStop,start),length=g.dot(delta,delta);
    if(g.sign(length)>0)for(const solid of solidsFor(ctx.state)){const center=g.point({x:String(solid.x),y:String(solid.y),z:String((solid.bottom+solid.top)/2n)}),time=g.clamp(g.div(g.dot(g.subtract(center,start),delta),length),g.n(0n),g.n(1n)),bound=radius+ceilSqrt(4000000000000n+(solid.top-solid.bottom)**2n/4n)+1n;if(g.cmp(g.distanceSquared(center,g.lerp(start,exactStop,time)),g.n(bound*bound))>0)continue;const distance=g.axisDistance(start,exactStop,solid);if(distance&&g.cmp(distance,g.n(radius*radius))<=0){const amount=radius?Number(BigInt(budget)*(radius-g.sqrtCeil(distance))/radius):budget;contribution.set(solid.id,Math.max(contribution.get(solid.id)??0,amount));}}
    stop=g.representative(exactStop);intent.target=remaining>0&&firstUnit&&(firstUnit.team!==intent.actor.team||intent.profile.friendlyFire)?firstUnit:undefined;for(const [id,amount] of contribution)addStructure(damage,id,amount);emit(ctx,'IBIS_TRACE',intent.actor.id,intent.target?.id,{groupId:`${ctx.tick}:${intent.group}`,details:{origin,aim:intent.aim,stop,budget,remainingPenetration:remaining,radius:String(radius),exactBodyImpact:exact}});return budget?Math.floor(20*intent.actor.stats.trion*remaining/budget):0;
  }
  for(const hit of rayIntersections(origin,beamEnd,solidsFor(ctx.state),true)){const absorb=absorption(hit,origin,beamEnd);addStructure(contribution,hit.solid.id,Math.min(remaining,absorb));if(remaining<=absorb){remaining=0;stop=hit.point;break;}remaining-=absorb;}
  intent.target=remaining>0&&firstUnit&&(firstUnit.team!==intent.actor.team||intent.profile.friendlyFire)?firstUnit:undefined;
  const radius=BigInt(Number(intent.profile.options?.localFractureCoefficient??500000))*BigInt(intent.actor.stats.trion)/6n,a=exactPoint(origin),b=exactPoint(stop),dx=b.x*a.d-a.x*b.d,dy=b.y*a.d-a.y*b.d,dz=b.z*a.d-a.z*b.d,len2=dx*dx+dy*dy+dz*dz;
  if(len2>0n){for(const solid of solidsFor(ctx.state)){const center={x:String(solid.x),y:String(solid.y),z:String((solid.bottom+solid.top)/2n)},p=exactPoint(center),vx=p.x*a.d-a.x,vy=p.y*a.d-a.y,vz=p.z*a.d-a.z,dot=vx*dx+vy*dy+vz*dz,t=dot<0n?rat(0n):dot*b.d>len2?rat(1n):rat(dot*b.d,len2),axis=interpolate(origin,stop,t),bound=radius+ceilSqrt(4000000000000n+(solid.top-solid.bottom)**2n/4n)+1n,centerDistance=distanceSquared(axis,center);if(centerDistance.n>bound*bound*centerDistance.d)continue;const d=axisSolidDistance(origin,stop,solid);if(d&&d.n<=radius*radius*d.d){const floor=integerSqrt(d.n/d.d),dc=floor*floor*d.d===d.n?floor:floor+1n,amount=radius?Number(BigInt(budget)*(radius-dc)/radius):budget;contribution.set(solid.id,Math.max(contribution.get(solid.id)??0,amount));}}}
  for(const [id,amount] of contribution)addStructure(damage,id,amount);
  emit(ctx,'IBIS_TRACE',intent.actor.id,intent.target?.id,{groupId:`${ctx.tick}:${intent.group}`,details:{origin,aim:intent.aim,stop,budget,remainingPenetration:remaining,radius:String(radius)}});return budget?Math.floor(20*intent.actor.stats.trion*remaining/budget):0;
}

function advanceProjectiles(ctx:Context):Blast[] {
  const blasts:Blast[]=[],remain:BattleState['projectiles']=[],solids=solidsFor(ctx.state),impacts=(ctx.state.effects.projectileImpacts??={}) as Record<string,ExactImpact>;
  for(const p of [...ctx.state.projectiles].sort(byId)){const profile=p.profile??weapon(ctx.content,p.profileId);if(!profile)throw new Error('UNKNOWN_PROJECTILE_PROFILE');if(p.bornAtTick===ctx.state.absoluteTick){remain.push(p);continue;}if(p.hp<=0){p.ageTicks++;if(p.fuse>0)p.fuse--;if(p.fuse===0){blasts.push({id:p.id,actorId:p.ownerId,profile,origin:p.position,budget:p.budget,radius:BigInt(p.radius),exactImpact:impacts[p.id]});delete impacts[p.id];emit(ctx,'DETONATE',p.ownerId,undefined,{groupId:`${ctx.tick}:1`,details:{projectileId:p.id,origin:p.position,budget:p.budget,radius:p.radius,reason:'FUSE'}});}else remain.push(p);continue;}const length=BigInt(p.length),travel=BigInt(p.travelledDistance)+BigInt(p.speed),next=interpolate(p.origin,p.aim,rat(travel>length?length:travel,length)),start=p.position,hits=rayIntersections(start,next,solids,true),first=hits[0],t=first?.enter;let contact=first?.point,contactId=first?.solid.id;
    let contactTime=t?rationalTime(t):undefined,terrainFirst=!!first;for(const u of ctx.state.units){if(!u.alive||u.id===p.ownerId)continue;const hit=bodyCylinderIntersection(start,next,pointFor(ctx.state,u,0));if(!hit)continue;const order=contactTime?compareCollisionTime(hit.enter,contactTime):-1;if(order<0||order===0&&!terrainFirst&&stableCompare(u.id,contactId??'')<0){contactTime=hit.enter;terrainFirst=false;contact=interpolate(start,next,timeBounds(hit.enter,256).upper);contactId=u.id;}}
    if(contactTime&&!terrainFirst){const exact=impactDescriptor(start,next,contactTime);if(exact){const body=ctx.state.units.find(u=>u.id===contactId)!;exact.cellId=cellFor(ctx.state,body).id;impacts[p.id]=exact;}}p.ageTicks++;p.travelledDistance=String(travel>length?length:travel);p.position=contact??next;
    if(!contact&&travel>=length&&p.waypoints&&(p.waypointIndex??0)+1<p.waypoints.length){p.waypointIndex=(p.waypointIndex??0)+1;p.origin=p.position;p.aim=p.waypoints[p.waypointIndex]!;p.travelledDistance='0';p.length=String(distanceCeil(p.origin,p.aim)||1n);remain.push(p);continue;}
    if(contact||travel>=length||p.ageTicks>=Number(profile.options?.maxAgeTicks??50)){if(p.fuse>0){p.hp=0;remain.push(p);emit(ctx,'PROJECTILE_FUSE',p.ownerId,undefined,{groupId:`${ctx.tick}:1`,details:{projectileId:p.id,origin:p.position,remainingFuse:p.fuse}});}else {blasts.push({id:p.id,actorId:p.ownerId,profile,origin:p.position,budget:p.budget,radius:BigInt(p.radius),exactImpact:impacts[p.id]});delete impacts[p.id];emit(ctx,'DETONATE',p.ownerId,undefined,{groupId:`${ctx.tick}:1`,details:{projectileId:p.id,origin:p.position,budget:p.budget,radius:p.radius,contactId,reason:contact?'CONTACT':travel>=length?'AIM':'LIFETIME'}});}}else remain.push(p);
  }ctx.state.projectiles=remain;return blasts;
}
function blastDamage(ctx:Context,blast:Blast,structures:Map<string,number>,units:Map<string,number>):void {
  if(blast.exactImpact){algebraicBlastDamage(ctx,blast,structures,units);return;}
  const solids=solidsFor(ctx.state),radius=blast.radius;
  const attenuate=(output:number,to:Point3):number=>{const dist=distanceSquared(blast.origin,to);if(dist.n>radius*radius*dist.d)return 0;const d=distanceCeil(blast.origin,to);return d>=radius?0:Number(BigInt(output)*(radius-d)/radius);};
  for(const solid of solids){if(!solid.element)continue;const point=nearestSolidPoint(blast.origin,solid);let amount=attenuate(blast.budget,point);if(amount<=0)continue;const hits=rayIntersections(blast.origin,point,solids,true);for(const hit of hits){if(hit.solid.id===solid.id)break;amount-=absorption(hit,blast.origin,point);if(amount<=0)break;}addStructure(structures,solid.id,Math.max(0,amount));}
  for(const target of ctx.state.units){if(!target.alive)continue;const point=pointFor(ctx.state,target,490000);let power=attenuate(Math.floor(blast.budget/6),point);if(power<=0)continue;for(const hit of rayIntersections(blast.origin,point,solids,true)){power-=absorption(hit,blast.origin,point);if(power<=0)break;}if(power<=0)continue;const def=defense(ctx,target,undefined,blast.origin,{...blast.profile,actionKind:'blast'},1),damage=Math.max(0,power-def.reduction);units.set(target.id,(units.get(target.id)??0)+damage);emit(ctx,'BLAST_DAMAGE',blast.actorId,target.id,{groupId:`${ctx.tick}:1`,power,reduction:def.reduction,damage,details:{projectileId:blast.id,blastOrigin:blast.origin,friendlyFire:true}});}
}
function applyDestruction(ctx:Context,damage:Map<string,number>):void {
  if(!damage.size)return;const beforeMap=ctx.state.map,oldGraph=surfaceGraph(beforeMap),elements=ctx.state.structures.map(e=>({...e,currentDurability:Math.max(0,e.currentDurability-(damage.get(e.id)??0))})),oldAlive=new Set(ctx.state.structures.filter(e=>e.currentDurability>0).map(e=>e.id)),supported=new Set<string>();
  for(const e of elements.sort((a,b)=>a.layerIndex-b.layerIndex||byId(a,b))){if(e.currentDurability>0&&(e.supportIds.length===0||e.supportIds.every(id=>supported.has(id))))supported.add(e.id);else e.currentDurability=0;}
  const removed=elements.filter(e=>oldAlive.has(e.id)&&e.currentDurability===0).map(e=>e.id);ctx.state.structures=elements.sort(byId);
  if(!removed.length){ctx.state.map={...beforeMap,structures:elements};return;}
  const remaining=new Map<string,StructureElement[]>();for(const e of elements.filter(e=>e.currentDurability>0)){const list=remaining.get(e.cellId)??[];list.push(e);remaining.set(e.cellId,list);}
  const changed=new Set(removed.map(id=>elements.find(e=>e.id===id)!.cellId)),cells=beforeMap.cells.map(cell=>{if(!changed.has(cell.id))return cell;const list=remaining.get(cell.id)??[],top=list.length?Math.max(...list.map(e=>cell.groundHeight+e.layerIndex+1)):cell.groundHeight,kind=list.length?'roof' as const:'ground' as const;return {...cell,buildingId:list.length?cell.buildingId:null,roofHeight:list.length?top:null,terrain:list.length?'building':'rubble',surfaces:[{id:list.length?`${cell.id}:roof@${top}`:`${cell.id}:ground`,cellId:cell.id,kind,z:top,walkable:true}],occluder:list.length?{kind:'solidColumn',minZ:cell.groundHeight,maxZ:top}:null};});
  ctx.state.map={...beforeMap,cells,structures:elements};ctx.state.geometryRevision++;const g=surfaceGraph(ctx.state.map),occupied=new Set(ctx.state.units.filter(u=>u.alive&&g.surfaces.has(u.surfaceId)).map(u=>u.surfaceId));
  for(const u of ctx.state.units.filter(u=>u.alive).sort(byId)){if(u.pendingMove&&(!g.surfaces.has(u.pendingMove.from)||!g.surfaces.has(u.pendingMove.to))){const move=u.pendingMove;u.ap+=move.cost;u.pendingMove=null;u.nextCommandAtTick=Math.max(u.nextCommandAtTick,ctx.tick+5);emit(ctx,'MOVE_CANCEL_TERRAIN',u.id,undefined,{apBefore:u.ap-move.cost,apAfter:u.ap,from:move.from,to:move.to});}
    if(g.surfaces.has(u.surfaceId))continue;const old=oldGraph.surfaces.get(u.surfaceId)!,same=cells.find(c=>c.id===old.cellId)!.surfaces.filter(s=>s.z<=old.z).sort((a,b)=>b.z-a.z||byId(a,b)),base=same[0];let support=same.find(s=>!occupied.has(s.id));
    if(!support){const candidates=[...g.surfaces.values()].filter(s=>s.z<=old.z&&!occupied.has(s.id)).map(s=>({s,path:base?findPath(ctx.state.map,base.id,s.id,true):null})).sort((a,b)=>(a.path?.path.length??Number.MAX_SAFE_INTEGER)-(b.path?.path.length??Number.MAX_SAFE_INTEGER)||(old.z-a.s.z)-(old.z-b.s.z)||byId(a.s,b.s));support=candidates[0]?.s;}
    if(support){const from=u.surfaceId;u.surfaceId=support.id;occupied.add(support.id);emit(ctx,'FORCED_FALL',u.id,undefined,{from,to:support.id,details:{fallDamage:0,geometryRevision:ctx.state.geometryRevision}});}else {u.alive=false;u.hp=0;u.ap=0;emit(ctx,'DEFEAT',undefined,u.id,{reasonCode:'TERRAIN_LOSS'});}
  }
  emit(ctx,'TERRAIN_CHANGE',undefined,undefined,{details:{removedElements:removed,structuralDamage:Object.fromEntries(damage),geometryRevision:ctx.state.geometryRevision,changedCells:[...changed].sort(stableCompare)}});updateObservations(ctx.state,ctx.content);
}
function processGroup(ctx:Context,intents:Intent[],group:number,blasts:Blast[]=[]):void {
  const unitsDamage=new Map<string,number>(),structureDamage=new Map<string,number>(),instant=new Set<string>(),readyBefore=new Map<string,number>(),fired:Intent[]=[];
  for(const u of ctx.state.units){const paired=intents.filter(i=>i.group===group&&i.actor.id===u.id&&i.target?.alive&&canAim(ctx.state,u,i.profile,i.target,i.aim,i.slot,ctx.content,i.waypoints));if(paired.length!==2)continue;let discount=0;for(const e of effects(u,ctx.content)){if(e.kind==='twin-snipe'&&u.main===e.values.weapon&&u.sub===e.values.weapon)discount+=Number(e.values.apDiscount??0);if(e.kind==='mixed-dual'&&paired[0]!.profile.actionKind!==paired[1]!.profile.actionKind)discount+=Number(e.values.apDiscount??0);}if(paired.reduce((n,i)=>n+i.cost,0)-discount<=u.ap&&discount>0){const first=paired.find(i=>i.slot==='main')!;first.cost=Math.max(1,first.cost-discount);}}
  for(const intent of intents.filter(i=>i.group===group).sort((a,b)=>stableCompare(a.actor.id,b.actor.id)||stableCompare(a.slot,b.slot)||stableCompare(a.id,b.id))){const u=intent.actor;if(!u.alive||!intent.target?.alive&&intent.target||!canAim(ctx.state,u,intent.profile,intent.target,intent.aim,intent.slot,ctx.content,intent.waypoints)||u.ap<intent.cost){if(!intent.followup)u.nextAttackAtTick=Math.max(u.nextAttackAtTick,ctx.tick+5);emit(ctx,'ATTACK_CANCEL',u.id,intent.target?.id,{groupId:`${ctx.tick}:${group}`,slot:intent.slot,reasonCode:!u.alive?'DEFEATED':u.ap<intent.cost?'AP_INSUFFICIENT':'CONDITIONS_CHANGED',details:{refundedReservation:intent.cost,waitApplied:0}});continue;}if(!readyBefore.has(u.id))readyBefore.set(u.id,u.readyAtTick);pay(ctx,u,intent.cost,intent.followup?'FOLLOWUP_FIRE':'FIRE',0,String(group),intent.slot,intent.target?.id,{weaponId:intent.profile.id,actionKind:intent.profile.actionKind,origin:pointFor(ctx.state,u,560000),aim:intent.aim});fired.push(intent);}
  for(const [id,before] of readyBefore){const u=ctx.state.units.find(u=>u.id===id)!,owned=fired.filter(i=>i.actor.id===id);if(!owned.every(i=>i.followup)){u.readyAtTick=Math.max(before,ctx.tick)+Math.max(...owned.filter(i=>!i.followup).map(i=>i.profile.waitUnits*5));u.nextAttackAtTick=ctx.tick+5;}emit(ctx,'ATTACK_WAIT',id,undefined,{groupId:`${ctx.tick}:${group}`,waitBefore:before,waitAfter:u.readyAtTick});}
  for(const intent of fired){const u=intent.actor,w=intent.profile;if(intent.followup){u.supportRemaining--;if(intent.target)delete u.effectState[`link:${intent.target.id}`];}if(u.activeCommand?.kind==='FIRE_AT'&&(u.activeCommand.slot??'main')===intent.slot)u.effectState.firedCommand=u.commandIndex;
    if(intent.target&&has(intent.target,ctx.content,'decoy')&&!u.effectState.decoyActions){u.effectState.decoyActions=6;u.effectState.decoyDefenseBp=8000;emit(ctx,'DECOY_DEBUFF',intent.target.id,u.id,{groupId:`${ctx.tick}:${group}`,details:{durationActions:6}});}
    if(w.powerModel==='meteor'){fireProjectile(ctx,intent);weaponAfterFire(u,w);delete u.effectState.synthesisReady;delete u.effectState.leadReady;continue;}let power:number;if(w.powerModel==='ibis'){const arrived=ibis(ctx,intent,structureDamage),base=20*u.stats.trion;power=base?Math.floor(arrived*powerFor(ctx,intent)/base):0;}else {power=powerFor(ctx,intent);const hit=intent.waypoints?.length?undefined:rayIntersections(pointFor(ctx.state,u,560000),intent.aim,solidsFor(ctx.state))[0];if(hit){addStructure(structureDamage,hit.solid.id,w.structureDamage??power);weaponAfterFire(u,w);continue;}}
    if(intent.target)applyUnitHit(ctx,intent,power,unitsDamage,instant);weaponAfterFire(u,w);delete u.effectState.leadReady;delete u.effectState.synthesisReady;delete u.effectState.curvedWaypoints;
    if(!intent.followup&&intent.target&&(w.actionKind==='melee'&&has(u,ctx.content,'melee-link')||['shot','sniper'].includes(w.actionKind)&&has(u,ctx.content,'shot-link'))){u.effectState[`link:${intent.target.id}`]=ctx.state.absoluteTick;u.effectState[`linkKind:${intent.target.id}`]=w.actionKind;u.effectState[`linkGroup:${intent.target.id}`]=`${ctx.state.absoluteTick}:${group}`;}
  }
  for(const blast of blasts.sort((a,b)=>stableCompare(a.actorId,b.actorId)||stableCompare(a.id,b.id)))blastDamage(ctx,blast,structureDamage,unitsDamage);
  for(const [id,damage] of unitsDamage){const u=ctx.state.units.find(u=>u.id===id)!;u.hp=Math.max(0,u.hp-damage);}for(const id of instant){const u=ctx.state.units.find(u=>u.id===id)!;u.hp=0;}
  for(const u of ctx.state.units){if(!u.alive||u.hp>0)continue;u.alive=false;u.ap=0;u.pendingMove=null;for(const team of ['A','B'] as const){const c=ctx.state.observations[team].contacts.find(c=>c.contactId===ctx.state.observations[team].contactLinks[u.id]);if(c?.channel==='visual'){c.defeated=true;c.hp=0;}}
    const credits=ctx.events.filter(e=>e.targetId===u.id&&e.groupId===`${ctx.tick}:${group}`&&e.damage!==undefined).sort((a,b)=>(b.damage??0)-(a.damage??0)||stableCompare(a.actorId??'',b.actorId??'')||stableCompare(a.id,b.id));emit(ctx,'DEFEAT',credits[0]?.actorId,u.id,{groupId:`${ctx.tick}:${group}`,details:{killCredit:credits[0]?.actorId??null}});}
  applyDestruction(ctx,structureDamage);updateObservations(ctx.state,ctx.content);
}
function followups(ctx:Context,intents:Intent[]):Intent[] {
  const result:Intent[]=[];for(const u of ctx.state.units.filter(u=>u.alive&&u.supportRemaining>0).sort(byId)){const w=weapon(ctx.content,u.main);if(!w?.enabled||w.attackAp===null||w.powerModel==='meteor')continue;const cost=has(u,ctx.content,'melee-link')&&w.actionKind==='melee'?0:has(u,ctx.content,'shot-link')&&['shot','sniper'].includes(w.actionKind)?1:null;if(cost===null||u.ap<cost)continue;const candidates=intents.filter(i=>i.actor.team===u.team&&i.actor.id!==u.id&&i.target?.alive&&i.group!==2&&ctx.events.some(e=>e.kind==='FIRE'&&e.actorId===i.actor.id&&e.groupId===`${ctx.tick}:${i.group}`)&&Number(u.effectState[`link:${i.target.id}`]??-1000)>=ctx.state.absoluteTick-5&&(cost===0?u.effectState[`linkKind:${i.target.id}`]==='melee':['shot','sniper'].includes(String(u.effectState[`linkKind:${i.target.id}`])))&&u.effectState[`linkGroup:${i.target.id}`]!==`${ctx.state.absoluteTick}:${i.group}`).sort((a,b)=>stableCompare(a.target!.id,b.target!.id));const target=candidates.find(i=>canAim(ctx.state,u,w,i.target,pointFor(ctx.state,i.target!,490000),'main',ctx.content))?.target;if(!target)continue;result.push({id:`${ctx.tick}:${u.id}:link`,actor:u,slot:'main',profile:w,target,aim:pointFor(ctx.state,target,490000),group:2,cost,followup:true,powerBp:10000});emit(ctx,'FOLLOWUP_PREPARED',u.id,target.id,{groupId:`${ctx.tick}:2`,effectIds:effects(u,ctx.content).filter(e=>e.kind.endsWith('-link')).map(e=>e.id)});}
  return result;
}

function landMoves(ctx:Context):void {
  const arriving=ctx.state.units.filter(u=>u.alive&&u.pendingMove?.completesAtTick===ctx.tick&&!u.pendingMove.awaitingContinuation),active=new Map(arriving.map(u=>[u.id,u])),blocked=new Set<string>(),occupied=new Map(ctx.state.units.filter(u=>u.alive).map(u=>[u.surfaceId,u.id]));
  const destinations=new Map<string,UnitState[]>();for(const u of arriving){const list=destinations.get(u.pendingMove!.to)??[];list.push(u);destinations.set(u.pendingMove!.to,list);}for(const list of destinations.values())if(list.length>1)for(const u of list)blocked.add(u.id);
  let changed=true;while(changed){changed=false;for(const u of arriving){if(blocked.has(u.id))continue;const target=occupied.get(u.pendingMove!.to);if(target&&(!active.has(target)||blocked.has(target))){blocked.add(u.id);changed=true;}}}
  for(const u of arriving){if(blocked.has(u.id))continue;const visited=new Set<string>(),chain:UnitState[]=[];let cur:UnitState|undefined=u;while(cur&&!blocked.has(cur.id)){if(visited.has(cur.id)){for(const unit of chain)blocked.add(unit.id);break;}visited.add(cur.id);chain.push(cur);const nextId=occupied.get(cur.pendingMove!.to);cur=nextId?active.get(nextId):undefined;}}
  for(const u of arriving.sort(byId)){const move=u.pendingMove!;
    if(blocked.has(u.id)&&ctx.state.effects.movementPolicy==='skip-occupied-v1'&&u.activeCommand&&['MOVE','TRACK','GUARD'].includes(u.activeCommand.kind)){
      const nextId=u.activeCommand.kind==='MOVE'?u.activeCommand.path?.[u.pathIndex+1]:move.continuationPath?.[0],from=getSurface(ctx.state.map,move.to),next=nextId?getSurface(ctx.state.map,nextId):undefined;
      const grasshopper=[u.main,u.sub].some(id=>weapon(ctx.content,id)?.options?.grasshopper===true);
      if(from&&next&&surfaceGraph(ctx.state.map).edges.get(from.id)?.some(s=>s.id===next.id)&&moveCost(from,next,grasshopper)!==null&&ctx.tick+5<150){
        u.pathIndex++;u.pendingMove={...move,to:next.id,via:[...(move.via??[]),move.to],...(move.continuationPath?{continuationPath:move.continuationPath.slice(1)}:{}),awaitingContinuation:true};
        emit(ctx,'MOVE_SKIP',u.id,undefined,{from:move.to,to:next.id,reasonCode:'OCCUPIED_CONTINUE'});continue;
      }
      // Finish this route rather than retrying the same occupied final surface.
      u.activeCommand=null;u.commandEndsAtTick=ctx.tick;
    }
    u.pendingMove=null;if(blocked.has(u.id)||!getSurface(ctx.state.map,move.to)){const before=u.ap;u.ap+=move.cost;u.nextCommandAtTick=ctx.tick+5;emit(ctx,'MOVE_CONFLICT',u.id,undefined,{from:move.from,to:move.to,apBefore:before,apAfter:u.ap,reasonCode:blocked.has(u.id)?'OCCUPIED_OR_CYCLE':'TERRAIN_LOSS'});}else {u.surfaceId=move.to;u.effectState.lastMovedAt=ctx.state.absoluteTick;u.pathIndex++;emit(ctx,'MOVE_LAND',u.id,undefined,{from:move.from,to:move.to});if(u.activeCommand?.kind==='MOVE'&&u.pathIndex>=(u.activeCommand.path?.length??0)){u.activeCommand=null;u.commandEndsAtTick=ctx.tick;u.nextCommandAtTick=ctx.tick;}}}
}
function startCommands(ctx:Context):void {
  for(const u of ctx.state.units){if(!u.alive||u.pendingMove||ctx.tick<u.readyAtTick||ctx.tick<u.nextCommandAtTick)continue;let cmd=u.activeCommand;
    if(cmd&&cmd.kind!=='MOVE'&&ctx.tick>=u.commandEndsAtTick){u.activeCommand=null;cmd=null;}
    if(cmd)continue;const plan=ctx.plans.get(u.id),next=plan?.commands[u.commandIndex+1];if(!next){u.activeCommand={kind:'HOLD',durationTicks:150};u.commandEndsAtTick=150;emit(ctx,'COMMAND_START',u.id,undefined,{reasonCode:'DEFAULT_HOLD',details:{kind:'HOLD',main:u.main,sub:u.sub,mainDirection:u.mainDirection,subDirection:u.subDirection,endsAtTick:150}});continue;}if(ctx.tick+5>=150)continue;
    u.commandIndex++;u.activeCommand=clone(next);u.pathIndex=0;u.effectState.commandStartedAt=ctx.tick;u.commandEndsAtTick=next.kind==='MOVE'?150:ctx.tick+(next.durationTicks??(next.kind==='WAIT'||next.kind==='HOLD'||next.kind==='FIRE_AT'||next.kind==='SPECIAL'?5:150));u.commandEndsAtTick=Math.min(150,u.commandEndsAtTick);u.nextCommandAtTick=ctx.tick+5;
    u.main=next.main??u.main;u.sub=next.sub??u.sub;if(!twinAllowed(u.skills,ctx.content,u.main,u.sub)){if(weapon(ctx.content,u.main)?.requiredSlots===2)u.sub='none';if(weapon(ctx.content,u.sub)?.requiredSlots===2&&weapon(ctx.content,u.sub)?.actionKind!=='option')u.main='none';}u.mainDirection=next.mainDirection??u.mainDirection;u.subDirection=next.subDirection??u.subDirection;u.mainMode=next.mainMode??u.mainMode??'attack';u.subMode=next.subMode??u.subMode??'attack';if(next.kind==='FULL_GUARD'){if(weapon(ctx.content,u.main)?.options?.supportsShieldMode)u.mainMode='shield';if(weapon(ctx.content,u.sub)?.options?.supportsShieldMode)u.subMode='shield';}if(Number(u.effectState.decoyActions??0)>0)u.effectState.decoyActions=Number(u.effectState.decoyActions)-1;
    const extra=extraCommand(ctx.state,u,next,ctx.content,ctx.tick);for(const event of extra)emit(ctx,event.kind,event.actorId,event.targetId,event);
    if(next.kind==='SPECIAL'&&!extra.length){const e=ctx.content.effects.find(e=>e.id===next.effectId&&e.enabled);if(e&&u.ap>=e.ap&&e.ap>=0){pay(ctx,u,e.ap,'SPECIAL',e.wait*5);u.effectState.special=e.values.special??e.kind;u.effectState.powerAdd=Number(e.values.powerAdd??0);}else emit(ctx,'SPECIAL_CANCEL',u.id,undefined,{reasonCode:'AP_OR_EFFECT_UNAVAILABLE'});}
    emit(ctx,'COMMAND_START',u.id,undefined,{details:{kind:next.kind,main:u.main,sub:u.sub,mainDirection:u.mainDirection,subDirection:u.subDirection,endsAtTick:u.commandEndsAtTick}});
  }
}
function startMoves(ctx:Context):void {
  for(const u of ctx.state.units){
    if(u.alive&&u.pendingMove?.awaitingContinuation){
      const move=u.pendingMove;if(ctx.tick<u.readyAtTick&&ctx.tick+5<150)continue;
      const from=getSurface(ctx.state.map,move.via!.at(-1)!),to=getSurface(ctx.state.map,move.to),gh=[u.main,u.sub].some(id=>weapon(ctx.content,id)?.options?.grasshopper===true);
      const baseCost=from&&to&&surfaceGraph(ctx.state.map).edges.get(from.id)?.some(s=>s.id===to.id)?moveCost(from,to,gh):null;
      const cost=baseCost===null?null:baseCost+weaponMoveExtraCost(ctx.state,u,move.to);
      if(cost===null||u.ap<cost||ctx.tick+5>=150){const before=u.ap;u.ap+=move.cost;u.pendingMove=null;u.activeCommand=null;u.commandEndsAtTick=ctx.tick;u.nextCommandAtTick=ctx.tick;
        emit(ctx,'MOVE_STOP',u.id,undefined,{from:move.from,to:move.to,apBefore:before,apAfter:u.ap,reasonCode:cost===null?'TERRAIN_LOSS':u.ap-move.cost<cost?'AP_INSUFFICIENT':'TURN_TIME_INSUFFICIENT'});continue;}
      pay(ctx,u,cost,'MOVE_BEGIN');u.pendingMove={...move,completesAtTick:ctx.tick+5,cost:move.cost+cost,awaitingContinuation:false};u.nextCommandAtTick=ctx.tick+5;
      emit(ctx,'MOVE_RESERVE',u.id,undefined,{from:from!.id,to:move.to,details:{completesAtTick:ctx.tick+5}});continue;
    }
    if(!u.alive||u.pendingMove||u.ap<=0||ctx.tick<u.readyAtTick||ctx.tick+5>=150)continue;const cmd=u.activeCommand;if(!cmd||!['MOVE','TRACK','GUARD'].includes(cmd.kind))continue;if(ctx.tick<u.nextCommandAtTick&&u.effectState.commandStartedAt!==ctx.tick)continue;
    const grasshopper=[u.main,u.sub].some(id=>weapon(ctx.content,id)?.options?.grasshopper===true),current=getSurface(ctx.state.map,u.surfaceId)!;let nextId:string|undefined;let continuationPath:string[]|undefined;
    if(cmd.kind==='MOVE'){nextId=cmd.path?.[u.pathIndex];if(!nextId){u.activeCommand=null;continue;}if(!getSurface(ctx.state.map,nextId)||!surfaceGraph(ctx.state.map).edges.get(current.id)?.some(s=>s.id===nextId)){const end=cmd.path?.at(-1);if(!end||!getSurface(ctx.state.map,end)){emit(ctx,'MOVE_STOP',u.id,undefined,{reasonCode:'DESTINATION_LOST'});u.activeCommand=null;continue;}const replanned=findPath(ctx.state.map,current.id,end,grasshopper);if(!replanned){emit(ctx,'MOVE_STOP',u.id,undefined,{reasonCode:'NO_ROUTE'});u.activeCommand=null;continue;}cmd.path=replanned.path;u.pathIndex=0;nextId=cmd.path[0];}}
    else {let targets:string[];if(cmd.kind==='GUARD'){const ally=ctx.state.units.find(a=>a.id===cmd.allyId&&a.alive&&a.team===u.team);if(!ally||hexDistance(cellFor(ctx.state,u),cellFor(ctx.state,ally))<=1)continue;targets=surfaceGraph(ctx.state.map).edges.get(ally.surfaceId)?.map(s=>s.id)??[];}else {const obs=ctx.state.observations[u.team],contact=obs.contacts.find(c=>c.contactId===cmd.contactId);if(!contact)continue;if(contact.channel==='visual'&&contact.surfaceId)targets=[contact.surfaceId];else {const cell=surfaceGraph(ctx.state.map).cells.get(contact.reportedCell);if(!cell)continue;targets=cell.surfaces.filter(s=>s.kind==='ground').map(s=>s.id);if(!targets.length)targets=ctx.state.map.cells.filter(c=>hexDistance(c,cell)===1).flatMap(c=>c.surfaces.filter(s=>s.kind==='ground').map(s=>s.id));}}
      const paths=targets.map(to=>findPath(ctx.state.map,current.id,to,grasshopper)).filter((p):p is {path:string[];cost:number}=>!!p).sort((a,b)=>a.cost-b.cost||a.path.length-b.path.length||stableCompare(a.path.join('\0'),b.path.join('\0')));nextId=paths[0]?.path[0];continuationPath=paths[0]?.path.slice(1);}
    if(!nextId)continue;const next=getSurface(ctx.state.map,nextId);if(!next)continue;const baseCost=moveCost(current,next,grasshopper),cost=baseCost===null?null:baseCost+weaponMoveExtraCost(ctx.state,u,nextId);if(cost===null||cost>u.ap)continue;pay(ctx,u,cost,'MOVE_BEGIN');u.pendingMove={from:u.surfaceId,to:nextId,completesAtTick:ctx.tick+5,cost,...(continuationPath?{continuationPath}:{})};u.nextCommandAtTick=ctx.tick+5;emit(ctx,'MOVE_RESERVE',u.id,undefined,{from:u.surfaceId,to:nextId,details:{completesAtTick:ctx.tick+5}});
  }
}
function publicEvents(state:BattleState,events:BattleEvent[],team:Team):BattleEvent[] {
  const own=new Set(state.units.filter(u=>u.team===team).map(u=>u.id)),obs=state.observations[team],visible=new Set(obs.contacts.filter(c=>c.channel==='visual').map(c=>c.contactId));const mapId=(id:string|undefined)=>id===undefined?undefined:own.has(id)?id:visible.has(obs.contactLinks[id]??'')?obs.contactLinks[id]:undefined;
  const result:BattleEvent[]=[];for(const event of events){if(['RADAR_DETECT','VISUAL_DETECT','CONTACT_LOST','TERRAIN_CHANGE'].includes(event.kind)){if(event.details?.disclosureTeam===team)result.push({id:`${team}:${event.turn}:${event.tick}:${result.length}`,turn:event.turn,tick:event.tick,groupId:event.groupId,kind:event.kind,targetId:event.targetId,reasonCode:event.reasonCode,description:event.kind,...(event.kind==='TERRAIN_CHANGE'?{details:{teamGeometryRevision:event.details.teamGeometryRevision,changedCells:event.details.changedCells}}:{})});continue;}const earlier=eventDisclosure.get(event)?.[team],actorId=earlier?.actorId??mapId(event.actorId),targetId=earlier?.targetId??mapId(event.targetId);if(!actorId&&!targetId)continue;const e:BattleEvent={id:`${team}:${event.turn}:${event.tick}:${result.length}`,turn:event.turn,tick:event.tick,groupId:event.groupId,kind:event.kind,actorId,targetId,reasonCode:event.kind==='MOVE_CANCEL_TERRAIN'?'MOVEMENT_STOPPED':event.reasonCode,description:event.kind,slot:event.slot,planRevision:actorId&&own.has(actorId)?event.planRevision:undefined,commandIndex:actorId&&own.has(actorId)?event.commandIndex:undefined};if(targetId&&own.has(targetId)){e.damage=event.damage;e.reduction=event.reduction;e.power=event.power;}if(actorId&&event.details?.visual){const visual=event.details.visual as Record<string,unknown>;e.details={visual:{weaponId:visual.weaponId,actionKind:visual.actionKind,origin:visual.origin,...(own.has(actorId)||targetId?{aim:visual.aim}:{})}};}
    if(actorId&&own.has(actorId)){e.description=event.description;if(event.details?.weaponId)e.details={...e.details,weaponId:event.details.weaponId};
      if(event.kind==='DETONATE'&&event.details?.origin)e.details={...e.details,origin:event.details.origin};
      e.apBefore=event.apBefore;e.apAfter=event.apAfter;e.waitBefore=event.waitBefore;e.waitAfter=event.waitAfter;e.from=event.from;e.to=event.to;}result.push(e);}return result;
}
function snapshot(state:BattleState):BattleState {const observation=(o:ObservationState):ObservationState=>({...o,contacts:o.contacts.map(cloneContact),contactLinks:{...o.contactLinks},visibleCells:immutableObjects.has(o.visibleCells)?o.visibleCells:[...o.visibleCells]});return {...state,units:state.units.map(cloneUnit),projectiles:clone(state.projectiles),effects:clone(state.effects),observations:{A:observation(state.observations.A),B:observation(state.observations.B)}};}
function makeFrame(ctx:Context,tick:number,events:BattleEvent[]):Frame {prepareImmutableState(ctx.state);for(const unit of ctx.state.units){immutable(unit.stats);immutable(unit.loadout);immutable(unit.skills);immutable(unit.rangeOverride);}const state=snapshot(ctx.state);return {tick,stateHash:stateHash(state),state,views:{A:projectState(state,'A'),B:projectState(state,'B')},events:clone(events),teamEvents:{A:publicEvents(state,events,'A'),B:publicEvents(state,events,'B')}};}
export function matchResult(state:BattleState):MatchResult|null {
  if(state.turn<=6)return null;const survivors={A:state.units.filter(u=>u.team==='A'&&u.alive).length,B:state.units.filter(u=>u.team==='B'&&u.alive).length},difference=Math.abs(survivors.A-survivors.B),threshold=STAGES[state.manifest.stage].threshold,winner:Team|'draw'=difference<threshold?'draw':survivors.A>survivors.B?'A':'B',points={A:winner==='draw'?STAGES[state.manifest.stage].points[1]:winner==='A'?STAGES[state.manifest.stage].points[0]:0,B:winner==='draw'?STAGES[state.manifest.stage].points[1]:winner==='B'?STAGES[state.manifest.stage].points[0]:0};return {winner,survivors,difference,threshold,reason:difference<threshold?'SURVIVOR_DIFFERENCE_BELOW_THRESHOLD':'SIX_TURNS_COMPLETE',points};
}
function algebraicBlastDamage(ctx:Context,blast:Blast,structures:Map<string,number>,units:Map<string,number>):void {
  const {geometry:g,point:origin}=impactGeometry(blast.exactImpact!),solids=solidsFor(ctx.state),radius=blast.radius,impactCell=surfaceGraph(ctx.state.map).cells.get(blast.exactImpact!.cellId??''),guardOrigin=impactCell?cellPoint(impactCell,0):g.representative(origin);
  const attenuate=(output:number,to:import('./algebraic').AlgebraicPoint):number=>{const distance=g.distanceSquared(origin,to);if(g.cmp(distance,g.n(radius*radius))>=0)return 0;const d=g.sqrtCeil(distance);return d>=radius?0:Number(BigInt(output)*(radius-d)/radius);};
  for(const solid of solids){if(!solid.element)continue;const point=g.nearest(origin,solid);let amount=attenuate(blast.budget,point);if(amount<=0)continue;for(const hit of g.intersections(origin,point,solids)){if(hit.solid.id===solid.id)break;amount-=g.absorption(hit,origin,point);if(amount<=0)break;}addStructure(structures,solid.id,Math.max(0,amount));}
  for(const target of ctx.state.units){if(!target.alive)continue;const point=g.point(pointFor(ctx.state,target,490000));let power=attenuate(Math.floor(blast.budget/6),point);if(power<=0)continue;for(const hit of g.intersections(origin,point,solids)){power-=g.absorption(hit,origin,point);if(power<=0)break;}if(power<=0)continue;const def=defense(ctx,target,undefined,guardOrigin,{...blast.profile,actionKind:'blast'},1),damage=Math.max(0,power-def.reduction);units.set(target.id,(units.get(target.id)??0)+damage);emit(ctx,'BLAST_DAMAGE',blast.actorId,target.id,{groupId:`${ctx.tick}:1`,power,reduction:def.reduction,damage,details:{projectileId:blast.id,blastOrigin:blast.origin,exactBodyImpact:blast.exactImpact,friendlyFire:true}});}
}
const temporaryEffectKeys=new Set(['firedCommand','special','powerAdd','leadReady','synthesisReady','synthesisMain','synthesisSub','curvedWaypoints','weaponPrepared','weaponPowerBp','weaponRange','leadWeaponReady','timerFuseTicks','timerHoundReady','idatenPath','idatenIndex','idatenNextTick','idatenEndsAt','idatenTurn','idatenDirection','idatenCornerUntil','opticalCloak','cloakUntilTurn','markTeam','markUntilTurn']);
function discardPreparations(u:UnitState):void {for(const key of Object.keys(u.effectState))if(key.startsWith('link')||temporaryEffectKeys.has(key))delete u.effectState[key];}
export function resolveTurn(input:BattleState,plans:TurnPlan[],content:ContentPack):TurnResolution {
  const signature=hashJSON(content);rememberContent(content,signature);if(input.manifest.contentVersion!==content.version||input.manifest.hashes.content!==signature)throw new Error('CONTENT_HASH_MISMATCH');if(effectCache.get(content)?.signature!==signature)effectCache.set(content,{signature,entries:new WeakMap()});if(input.turn>6)throw new Error('MATCH_ENDED');const duplicates=new Set<string>();for(const plan of plans){if(duplicates.has(plan.unitId))throw new Error('DUPLICATE_PLAN');duplicates.add(plan.unitId);const valid=validatePlan(input,plan,content);if(!valid.ok)throw new Error(valid.errors.join(';'));}
  const state=snapshot(input);state.units.sort(byId);observationEvents.set(state,[]);const ctx:Context={state,content,tick:0,events:[],serial:0,plans:new Map(plans.map(p=>[p.unitId,clone(p)]))};
  for(const u of state.units){u.ap=u.alive?u.stats.ap:0;u.commandIndex=-1;u.readyAtTick=0;u.nextAttackAtTick=0;u.nextCommandAtTick=0;u.activeCommand=null;u.commandEndsAtTick=0;u.pathIndex=0;u.pendingMove=null;u.supportRemaining=u.stats.support;discardPreparations(u);}
  for(const u of state.units)if(u.alive)for(const e of effects(u,content))if(e.kind==='loadout-aptitude'&&[...u.loadout.main,...u.loadout.sub].some(id=>{const w=weapon(content,id);return !!w&&familyMatches(w,String(e.values.family));}))u.ap+=Number(e.values.ap??0);
  const frames:Frame[]=[makeFrame(ctx,-1,[])],checkpoints:Frame[]=[frames[0]!],fullEvents:BattleEvent[]=[];
  for(let tick=0;tick<150;tick++){ctx.tick=tick;ctx.events=[];state.absoluteTick=(state.turn-1)*150+tick;for(const u of state.units)if(Number(u.effectState.leadExpiresAt??Number.MAX_SAFE_INTEGER)<=state.absoluteTick){delete u.effectState.lead;delete u.effectState.leadExpiresAt;}for(const event of weaponTick(state,content,tick))emit(ctx,event.kind,event.actorId,event.targetId,event);landMoves(ctx);startCommands(ctx);updateObservations(state,content);const intents=buildIntents(ctx),blasts=advanceProjectiles(ctx);processGroup(ctx,intents,0);processGroup(ctx,intents,1,blasts);processGroup(ctx,followups(ctx,intents),2);startMoves(ctx);
    if(tick===149){for(const u of state.units){u.activeCommand=null;u.pendingMove=null;u.readyAtTick=0;u.nextAttackAtTick=0;u.nextCommandAtTick=0;u.commandIndex=-1;u.pathIndex=0;discardPreparations(u);}if(state.turn===6){for(const p of state.projectiles)emit(ctx,'PROJECTILE_DISCARD',p.ownerId,undefined,{reasonCode:'MATCH_END',details:{projectileId:p.id}});state.projectiles=[];}}
    updateObservations(state,content);for(const event of observationEvents.get(state)??[])emit(ctx,event.kind,undefined,event.contactId,{details:{disclosureTeam:event.team,...(event.kind==='TERRAIN_CHANGE'?{changedCells:event.changedCells,teamGeometryRevision:event.teamGeometryRevision}:{})}});observationEvents.set(state,[]);fullEvents.push(...ctx.events);const frame=makeFrame(ctx,tick,ctx.events);frames.push(frame);if(tick%10===0||tick===149)checkpoints.push(frame);
  }
  const nextState=snapshot(state);nextState.turn++;nextState.absoluteTick=(nextState.turn-1)*150;const result=matchResult(nextState);if(result)nextState.effects.matchResult=result;return {nextState,fullEvents,frames,checkpoints,result};
}
export function createFixedPlans(state:BattleState,team:Team,content:ContentPack):TurnPlan[] {
  const publicMap=projectState(state,team).map,center=[...publicMap.cells].sort((a,b)=>hexDistance(a,{q:0,r:0})-hexDistance(b,{q:0,r:0})||byId(a,b)).flatMap(c=>c.surfaces)[0]!;
  return state.units.filter(u=>u.team===team&&u.alive).map(u=>{const gh=[u.main,u.sub].some(id=>weapon(content,id)?.options?.grasshopper),p=findPath(publicMap,u.surfaceId,center.id,!!gh),path:string[]=[];let ap=u.stats.ap,from=getSurface(publicMap,u.surfaceId)!;for(const id of p?.path??[]){const to=getSurface(publicMap,id)!,cost=moveCost(from,to,!!gh)!;if(cost>ap||path.length>=28)break;path.push(id);ap-=cost;from=to;}return {unitId:u.id,planRevision:0,commands:path.length?[{kind:'MOVE',path,mainDirection:team==='A'?270:90,subDirection:team==='A'?270:90}]:[{kind:'HOLD',durationTicks:150}]};});
}
