import { describe, expect, it } from 'vitest';
import { bodyCylinderIntersection, cellPoint, compileMatch, impactDescriptor, impactGeometry, integerSqrt, QuadraticGeometry, resolveTurn, updateObservations } from '@battle/engine';
import type { Point3 } from '@battle/contracts';
import { appendTurn, createReplay, replayFrame, validateReplay } from '@battle/replay';
import { calibrationFixture, fixtureContent, fixtureMap, fixtureRoster } from '../fixtures/battle';
describe('algebraic body-impact predicates remain exact after serialization',()=>{
  it('nearest prism and integer distance preserve an exact sphere tangency from an irrational body impact',()=>{
    const x=1732051n,center={x:String(7n*x),y:'3000000',z:'700000'},vx=6n*x,vy=2000000n,l=vx*vx+vy*vy,radius=280000n,n=integerSqrt(l+radius*radius)+1n,offset=n*n-radius*radius-l,denominator=2n*l;
    const endpoint=(sign:bigint):Point3=>({x:String(BigInt(center.x)*denominator+offset*vx-sign*vy*denominator),y:String(BigInt(center.y)*denominator+offset*vy+sign*vx*denominator),z:String(700000n*denominator),denominator:String(denominator)}),from=endpoint(-1n),to=endpoint(1n),hit=bodyCylinderIntersection(from,to,center)!,descriptor=impactDescriptor(from,to,hit.enter)!;
    expect(descriptor).toBeDefined();const {geometry:g,point}=impactGeometry(descriptor),solid={id:'prism',cellId:'c:0:0',x:0n,y:0n,bottom:0n,top:1400000n},nearest=g.nearest(point,solid),distance=g.distanceSquared(point,nearest);
    expect(g.cmp(distance,g.n(n*n))).toBe(0);expect(g.sqrtCeil(distance)).toBe(n);expect(g.cmp(distance,g.n((n-1n)**2n))).toBe(1);expect(g.cmp(distance,g.n((n+1n)**2n))).toBe(-1);
  });
  it('finite-cylinder radial tangency uses the exact body root rather than its display representative',()=>{
    const from={x:'-280000',y:'280000',z:'0',denominator:'3'},to={x:'280000',y:'280000',z:'0',denominator:'3'},center={x:'0',y:'0',z:'0'},hit=bodyCylinderIntersection({...from,x:'-840000'},{...to,x:'840000'},center)!,descriptor=impactDescriptor({...from,x:'-840000'},{...to,x:'840000'},hit.enter)!,{geometry:g,point}=impactGeometry(descriptor),root=g.div(g.scale(point.x,-3n),g.n(560000n));
    const solid={id:'prism',cellId:'c:0:0',x:0n,y:0n,bottom:0n,top:1400000n},a={x:g.neg(root),y:g.add(g.n(2000000n),root),z:g.add(g.n(1400000n),root)},b={...a,x:root},distance=g.axisDistance(a,b,solid)!;
    expect(g.cmp(distance,g.n(4n))).toBe(0);expect(g.sqrtCeil(distance)).toBe(2n);const reversed=g.axisDistance(b,a,solid)!;expect(g.cmp(reversed,distance)).toBe(0);
  });
  it('fuse and replay retain exact impact descriptors; changing only the rational display point cannot change blast power',()=>{
    const state=compileMatch(fixtureMap(),fixtureContent,{A:fixtureRoster,B:fixtureRoster},8),actor=state.units[0]!,target=state.units.find(u=>u.team==='B')!;state.units=[actor,target];actor.surfaceId='c:-1:0:ground';target.surfaceId='c:0:0:ground';actor.main=actor.sub=target.main=target.sub='none';const profile={...fixtureContent.weapons.find(w=>w.id==='meteor')!,options:{fuse:2}};
    state.projectiles=[{id:'precision-projectile',ownerId:actor.id,team:'A',profileId:'meteor',profile,origin:{x:'-600000',y:'100000',z:'490000'},aim:{x:'600000',y:'100000',z:'490000'},position:{x:'-600000',y:'100000',z:'490000'},travelledDistance:'0',speed:'1200000',length:'1200000',ageTicks:0,bornAtTick:-1,budget:6*280001,radius:'280001',hp:1,fuse:2}];updateObservations(state,fixtureContent);
    const result=resolveTurn(state,[],fixtureContent),impact=result.frames[1]!.state;expect(impact.effects.projectileImpacts).toHaveProperty('precision-projectile');expect(result.fullEvents.find(e=>e.kind==='BLAST_DAMAGE')!.power).toBe(1);expect(result.nextState.units.find(u=>u.id===target.id)!.hp).toBe(99);
    const replay=appendTurn(createReplay(state),[],result);expect(validateReplay(replay).ok).toBe(true);const recorded=replayFrame(replay,1,0);expect(recorded.effects.projectileImpacts).toEqual(impact.effects.projectileImpacts);
    recorded.turn=2;recorded.projectiles[0]!.position={x:'17320510',y:'0',z:'490000'};const guarded=recorded.units.find(u=>u.id===target.id)!;guarded.sub='shield';guarded.subDirection=180;const continued=resolveTurn(recorded,[],fixtureContent),hit=continued.fullEvents.find(e=>e.kind==='BLAST_DAMAGE')!;expect(hit.power).toBe(1);expect(hit.reduction).toBe(24);expect(continued.nextState.units.find(u=>u.id===target.id)!.hp).toBe(100);
  });
  it('quadratic-field conjugation and comparisons never approximate cancellation',()=>{const g=new QuadraticGeometry(2n),root=g.n(0n,1n);expect(g.cmp(g.mul(root,root),g.n(2n))).toBe(0);expect(g.cmp(g.div(g.n(1n),g.add(g.n(1n),root)),g.sub(root,g.n(1n)))).toBe(0);expect(g.sign(g.sub(root,g.n(14142135623730950488n,0n,10000000000000000000n)))).toBe(1);});
  it('IB executes exact body-end cap, penetration absorption and local fracture with stable input order',()=>{const fixture=calibrationFixture('residential'),state=compileMatch(fixture.map,fixtureContent,{A:fixtureRoster,B:fixtureRoster},8),actor=state.units[0]!,target=state.units.find(u=>u.team==='B')!;state.units=[actor,target];actor.surfaceId=fixture.originSurface;actor.stats.trion=25;actor.main='ibis';actor.sub='none';actor.mainDirection=30;target.surfaceId='c:0:1:roof';target.main=target.sub='none';const cell=state.map.cells.find(c=>c.id==='c:0:1')!,aim=cellPoint(cell,2,490000);updateObservations(state,fixtureContent);state.observations.A.visibleCells=[...state.observations.A.visibleCells,cell.id];const plan={unitId:actor.id,planRevision:0,commands:[{kind:'FIRE_AT' as const,aim}]},reversed=structuredClone(state);reversed.units.reverse();reversed.map.cells.reverse();const result=resolveTurn(state,[plan],fixtureContent),again=resolveTurn(reversed,[plan],fixtureContent);expect(result.fullEvents.find(e=>e.kind==='IBIS_TRACE')!.details!.exactBodyImpact).toBeDefined();expect(result.nextState.structures.some(e=>e.currentDurability===0)).toBe(true);expect(result.frames.map(f=>f.stateHash)).toEqual(again.frames.map(f=>f.stateHash));});
});
