import { describe, expect, it } from 'vitest';
import { compileMatch, projectState, resolveTurn, updateObservations } from '@battle/engine';
import { measureCalibration } from '../fixtures/calibration';
import { calibrationFixture, fixtureContent, fixtureMap, fixtureRoster } from '../fixtures/battle';
describe('D1.1 projectile, local structure destruction and B1 measurement',()=>{
  it('D11-T4 residential and separate mall fixtures measure B1 honestly',()=>{const values={residentialT6:measureCalibration('residential',6),residentialT25:measureCalibration('residential',25),mallT6:measureCalibration('mall',6),mallT25:measureCalibration('mall',25)};expect(values.residentialT6.initialElements).toBe(8);expect(values.mallT6.initialElements).toBe(108);expect(values.residentialT25.removedElements).toBeGreaterThan(values.residentialT6.removedElements);expect(values.mallT25.removedElements).toBeGreaterThan(values.mallT6.removedElements);for(const value of Object.values(values))expect(value.calibrated).toBe(false);console.info('B1 fixture measurements',Object.fromEntries(Object.entries(values).map(([id,{state:_,...measurement}])=>[id,measurement])));});
  it('D11-T2/D11-T5 new projectiles wait until next tick and survive owner death across turns',()=>{const s=compileMatch(fixtureMap(),fixtureContent,{A:fixtureRoster,B:fixtureRoster},1),u=s.units[0]!;s.units=[u];u.surfaceId='c:-8:0:ground';u.main='meteor';u.sub='none';u.mainDirection=0;updateObservations(s,fixtureContent);const r=resolveTurn(s,[{unitId:u.id,planRevision:0,commands:[{kind:'WAIT',durationTicks:140},{kind:'FIRE_AT',aim:{x:'0',y:'0',z:'0'}}]}],fixtureContent);expect(r.frames.find(f=>f.tick===140)!.state.projectiles[0]!.ageTicks).toBe(0);expect(r.nextState.projectiles).toHaveLength(1);r.nextState.units[0]!.alive=false;r.nextState.units[0]!.hp=0;const next=resolveTurn(r.nextState,[],fixtureContent);expect(next.fullEvents.some(e=>e.kind==='DETONATE')).toBe(true);expect(next.nextState.projectiles).toHaveLength(0);});
  it('D11-T2 blast includes allies and owner without a hit roll',()=>{const s=compileMatch(fixtureMap(),fixtureContent,{A:fixtureRoster,B:fixtureRoster},1);s.units=s.units.slice(0,2);s.units[0]!.surfaceId='c:0:0:ground';s.units[0]!.main='meteor';s.units[0]!.mainDirection=0;s.units[0]!.sub='none';s.units[1]!.surfaceId='c:1:0:ground';updateObservations(s,fixtureContent);const r=resolveTurn(s,[{unitId:s.units[0]!.id,planRevision:0,commands:[{kind:'FIRE_AT',aim:{x:'3464102',y:'0',z:'0'}}]}],fixtureContent);expect(r.nextState.units.every(u=>u.hp<100)).toBe(true);expect(r.fullEvents.filter(e=>e.kind==='RANDOM')).toHaveLength(0);});
  it('D11-T3 column support collapses and roof occupants force down',()=>{const f=calibrationFixture('residential'),s=compileMatch(f.map,fixtureContent,{A:fixtureRoster,B:fixtureRoster},1);s.units=s.units.slice(0,2);const shooter=s.units[0]!,roof=s.units[1]!;shooter.surfaceId=f.originSurface;shooter.main='ibis';shooter.sub='none';shooter.mainDirection=0;shooter.stats.trion=25;roof.surfaceId='c:0:0:roof';updateObservations(s,fixtureContent);s.observations.A.visibleCells=[...s.observations.A.visibleCells,f.aimCell];const r=resolveTurn(s,[{unitId:shooter.id,planRevision:0,commands:[{kind:'FIRE_AT',aim:f.aim}]}],fixtureContent);expect(r.nextState.geometryRevision).toBeGreaterThan(0);expect(r.nextState.units[1]!.surfaceId).not.toBe('c:0:0:roof');expect(r.fullEvents.some(e=>e.kind==='FORCED_FALL')).toBe(true);expect(r.nextState.units.every(u=>!u.alive||r.nextState.map.cells.some(c=>c.surfaces.some(s=>s.id===u.surfaceId)))).toBe(true);});
  it('R13-T8 unseen terrain change preserves opponent geometry and revision',()=>{const f=calibrationFixture('residential'),s=compileMatch(f.map,fixtureContent,{A:fixtureRoster,B:fixtureRoster},1);s.units=[s.units[0]!,s.units.find(u=>u.team==='B')!];const a=s.units[0]!,b=s.units[1]!;a.surfaceId=f.originSurface;a.main='ibis';a.stats.trion=25;a.mainDirection=0;b.surfaceId='c:11:-8:ground';updateObservations(s,fixtureContent);s.observations.A.visibleCells=[...s.observations.A.visibleCells,f.aimCell];const before=projectState(s,'B'),r=resolveTurn(s,[{unitId:a.id,planRevision:0,commands:[{kind:'FIRE_AT',aim:f.aim}]}],fixtureContent),after=projectState(r.nextState,'B');expect(after.teamGeometryRevision).toBe(before.teamGeometryRevision);expect(after.map.cells.find(c=>c.id===f.aimCell)!.surfaces).toEqual(before.map.cells.find(c=>c.id===f.aimCell)!.surfaces);expect(r.frames.flatMap(f=>f.teamEvents.B).some(e=>e.kind==='TERRAIN_CHANGE')).toBe(false);});
});
