import { describe, expect, it } from 'vitest';
import type { ContentPack, EffectDefinition, TurnPlan, WeaponProfile } from '@battle/contracts';
import { compileMatch, hashJSON, initializeHashing, resolveTurn, stateHash, updateObservations } from '@battle/engine';
import { fixtureContent, fixtureMap, fixtureRoster } from '../fixtures/battle';
function setup(kind:string,values:EffectDefinition['values'],owner:'attacker'|'defender'='attacker') {
  const content=structuredClone(fixtureContent),id=`${kind}-test`,e:EffectDefinition={id,name:kind,enabled:true,status:'fixture',triggerHook:'DEFEND',priority:50,ap:0,wait:0,stackKey:id,maxStacks:1,duration:'match',kind,values,description:'individual boundary fixture',evidenceStatus:'original',sourceIds:[]};content.effects=[e];content.characters[owner==='attacker'?0:1]!.skills=[id];
  const shot:WeaponProfile={...content.weapons[0]!,id:'shot',family:'fixture-shot',actionKind:'shot',powerModel:'trion',basePower:3,baseHit:100,range:8,defenseAp:null,defenseModel:null};content.weapons.push(shot);for(const p of content.characters){p.defaultLoadout.main=['none','blade','shot','ibis'];p.defaultLoadout.sub=['none','shield','shot','bagworm'];}
  const state=compileMatch(fixtureMap(),content,{A:fixtureRoster,B:fixtureRoster},3),a=state.units.find(u=>u.id==='A-01-01')!,b=state.units.find(u=>u.id==='B-02-01')!;state.units=[a,b];a.surfaceId='c:0:0:ground';b.surfaceId='c:1:0:ground';a.mainDirection=0;a.subDirection=0;b.mainDirection=180;b.subDirection=180;a.main='shot';a.sub='none';b.main='none';b.sub='none';updateObservations(state,content);return {state,a,b,content};
}
function manifest(state:ReturnType<typeof setup>['state'],content:ContentPack):void {state.manifest={...state.manifest,contentVersion:content.version,hashes:{...state.manifest.hashes,content:hashJSON(content)}};}
describe('individual C1 effects have distinct executable predicates',()=>{
  it('melee-defense permits a paid sheathed blade guard without active shield',()=>{const {state,a,b,content}=setup('melee-defense',{requiresLoadoutMelee:true},'defender');a.main='blade';a.stats.attack=1;b.stats.defense=4;const result=resolveTurn(state,[],content),hit=result.fullEvents.find(e=>e.kind==='DAMAGE'&&e.tick===0)!;expect(hit.reduction).toBe(16);expect(hit.damage).toBe(0);expect(result.frames[1]!.state.units[1]!.ap).toBe(16);});
  it('learn-defense starts on the second matching attacker/profile, not the first',()=>{const {state,b,content}=setup('learn-defense',{repeat:2,bp:12500},'defender');b.sub='shield';b.stats.trion=0;b.stats.defense=5;const result=resolveTurn(state,[],content),hits=result.fullEvents.filter(e=>e.kind==='DAMAGE');expect(hits[0]!.reduction).toBe(10);expect(hits[1]!.reduction).toBe(12);});
  it('composite dual ordinary shots classify only SUB as sniper and double it',()=>{const {state,a,content}=setup('composite-dual',{subPowerBp:20000,subActionKind:'sniper'});a.sub='shot';const result=resolveTurn(state,[],content),hits=result.fullEvents.filter(e=>e.kind==='DAMAGE'&&e.tick===0);expect(hits.find(e=>e.slot==='main')!.power).toBe(18);expect(hits.find(e=>e.slot==='sub')!.power).toBe(36);expect(result.frames[1]!.state.units[0]!.ap).toBe(13);expect(result.frames[1]!.state.units[0]!.readyAtTick).toBe(10);});
  it('pin-sniper tests target activity for both power and hit',()=>{const stationary=setup('pin-sniper',{hit:15,bp:12000});stationary.content.weapons.find(w=>w.id==='ibis')!.baseHit=85;manifest(stationary.state,stationary.content);stationary.a.main='ibis';const standing=resolveTurn(stationary.state,[],stationary.content);expect(standing.fullEvents.find(e=>e.kind==='RANDOM')!.random!.percent).toBe(100);expect(standing.fullEvents.find(e=>e.kind==='DAMAGE')!.power).toBe(144);const moving=setup('pin-sniper',{hit:15,bp:12000});moving.content.weapons.find(w=>w.id==='ibis')!.baseHit=85;manifest(moving.state,moving.content);moving.a.main='ibis';const plan:TurnPlan={unitId:moving.b.id,planRevision:0,commands:[{kind:'MOVE',path:['c:2:0:ground']}]},walking=resolveTurn(moving.state,[plan],moving.content);expect(walking.fullEvents.find(e=>e.kind==='RANDOM')!.random!.percent).toBe(85);expect(walking.fullEvents.find(e=>e.kind==='DAMAGE')!.power).toBe(120);});
  it('sniper pressure consumes AP even when a successful hit is evaded',()=>{const {state,a,b,content}=setup('sniper-pressure',{apDrain:1});a.main='ibis';b.stats.evasion=20;const ib=content.weapons.find(w=>w.id==='ibis')!;ib.baseHit=100;manifest(state,content);const result=resolveTurn(state,[],content);expect(result.fullEvents.some(e=>e.kind==='EVADE'&&e.tick===0)).toBe(true);expect(result.fullEvents.some(e=>e.kind==='SNIPER_PRESSURE'&&e.tick===0)).toBe(true);expect(result.frames[1]!.state.units[1]!.ap).toBe(16);expect(result.frames[1]!.state.units[1]!.hp).toBe(100);});
});
describe('canonical hashing accelerates without changing the bytes or hiding mutation',()=>{
  it('streamed JS and WASM SHA-256 equal full canonical JSON including large rational strings',async()=>{const {state}=setup('mobile-sniper',{});state.effects.large={x:'1234567890123456789012345678901234567890',denominator:'98765432101234567890'};const reference=hashJSON(state),before=stateHash(state);await initializeHashing();expect(before).toBe(reference);expect(stateHash(state)).toBe(reference);});
  it('compiled terrain mutation throws and mutable external terrain always hashes fresh',()=>{const {state}=setup('mobile-sniper',{});expect(()=>{state.map.cells[0]!.roofHeight=10;}).toThrow(TypeError);const external=structuredClone(state),before=stateHash(external);external.map.cells[0]!.roofHeight=10;expect(stateHash(external)).not.toBe(before);external.map.cells[0]!.roofHeight=11;expect(stateHash(external)).not.toBe(before);});
});
