import { describe, expect, it } from 'vitest';
import { axisSolidDistance, bodyCylinderIntersection, compareCollisionTime, compareRational, compileMatch, projectState, quadraticTime, rat, rationalTime, resolveTurn, updateObservations, validateRoster } from '@battle/engine';
import type { Solid } from '@battle/engine';
import { calibrationFixture, fixtureContent, fixtureMap, fixtureRoster } from '../fixtures/battle';
const solid:Solid={id:'hex',cellId:'hex',x:0n,y:0n,bottom:0n,top:1400000n};
describe('exact finite cylinder and root ordering',()=>{
  it('finite IB volume excludes solids beyond a flat cap even within a spherical endpoint radius',()=>{const shifted={...solid,x:3464102n};expect(axisSolidDistance({x:'0',y:'0',z:'700000'},{x:'1700000',y:'0',z:'700000'},shifted)).toBe(null);});
  it('minimizes the radial convex quadratic along clipped prism edges and is reversible',()=>{const from={x:'-4000000',y:'3000000',z:'700000'},to={x:'4000000',y:'3000000',z:'700000'},distance=axisSolidDistance(from,to,solid)!;expect(compareRational(distance,rat(1000000000000n))).toBe(0);expect(compareRational(axisSolidDistance(to,from,solid)!,distance)).toBe(0);expect(axisSolidDistance({x:'-4000000',y:'0',z:'700000'},{x:'4000000',y:'0',z:'700000'},solid)).toEqual(rat(0n));});
  it('refines root intervals beyond128 bits instead of ordering indistinguishable approximations',()=>{const d=1n<<220n,first=quadraticTime(1n,0n,-2n,1),later=quadraticTime(d*d,-2n*d,1n-2n*d*d,1);expect(compareCollisionTime(first,later)).toBe(-1);expect(compareCollisionTime(later,first)).toBe(1);expect(compareCollisionTime(first,quadraticTime(7n,0n,-14n,1))).toBe(0);});
  it('uses closed body boundaries, clipping Z and rational terrain ties exactly',()=>{const from={x:'-560000',y:'280000',z:'840000'},to={x:'560000',y:'280000',z:'840000'},center={x:'0',y:'0',z:'0'},hit=bodyCylinderIntersection(from,to,center)!;expect(compareCollisionTime(hit.enter,rationalTime(rat(1n,2n)))).toBe(0);expect(compareCollisionTime(hit.enter,hit.exit)).toBe(0);expect(bodyCylinderIntersection({...from,z:'840001'},{...to,z:'840001'},center)).toBe(null);});
});
describe('ray extent and side observation events',()=>{
  it('shows an active Raygust mode only through visual contacts, stripping it from radar and lost reports',()=>{const c=structuredClone(fixtureContent);c.weapons.push({...c.weapons[0]!,id:'raygust',defenseModel:'raygust',options:{supportsShieldMode:true}});c.characters[0]!.defaultLoadout.main[1]='raygust';const state=compileMatch(fixtureMap(),c,{A:fixtureRoster,B:fixtureRoster},8),a=state.units[0]!,b=state.units.find(u=>u.team==='B')!;state.units=[a,b];a.surfaceId='c:0:0:ground';b.surfaceId='c:1:0:ground';a.main=a.sub='none';b.main='raygust';b.sub='none';b.mainMode='shield';b.subMode='attack';updateObservations(state,c);const seen=projectState(state,'A').contacts.find(c=>c.channel==='visual')!;expect(seen.mainMode).toBe('shield');expect(seen.subMode).toBe('attack');a.surfaceId='c:-10:0:ground';updateObservations(state,c);const radar=projectState(state,'A').contacts.find(c=>c.channel==='radar')!;expect(radar.mainMode).toBeUndefined();expect(radar.subMode).toBeUndefined();b.sub='bagworm';updateObservations(state,c);const lost=projectState(state,'A').contacts.find(c=>c.channel==='lost')!;expect(lost.mainMode).toBeUndefined();expect(lost.subMode).toBeUndefined();});
  it('IB terrain aim gives a direction; a penetrating beam continues beyond the clicked cell',()=>{const f=calibrationFixture('residential'),state=compileMatch(f.map,fixtureContent,{A:fixtureRoster,B:fixtureRoster},8),actor=state.units[0]!;state.units=[actor];actor.surfaceId=f.originSurface;actor.main='ibis';actor.sub='none';actor.mainDirection=0;actor.stats.trion=25;updateObservations(state,fixtureContent);state.observations.A.visibleCells=[...state.observations.A.visibleCells,f.aimCell];const result=resolveTurn(state,[{unitId:actor.id,planRevision:0,commands:[{kind:'FIRE_AT',aim:f.aim}]}],fixtureContent),trace=result.fullEvents.find(e=>e.kind==='IBIS_TRACE')!;expect(trace.details!.stop).not.toEqual(f.aim);expect(result.nextState.structures.filter(e=>e.currentDurability===0)).toHaveLength(8);});
  it('radar, lost and visual events disclose contact IDs only to the observing team',()=>{const state=compileMatch(fixtureMap(),fixtureContent,{A:fixtureRoster,B:fixtureRoster},8),a=state.units[0]!,b=state.units.find(u=>u.team==='B')!;state.units=[a,b];a.surfaceId='c:0:0:ground';b.surfaceId='c:8:0:ground';a.main='none';a.sub='none';b.main='none';b.sub='bagworm';state.observations.A.contacts=[];state.observations.A.contactLinks={};updateObservations(state,fixtureContent);const result=resolveTurn(state,[{unitId:a.id,planRevision:0,commands:[{kind:'MOVE',path:['c:1:0:ground','c:2:0:ground']}]},{unitId:b.id,planRevision:0,commands:[{kind:'WAIT',durationTicks:5,sub:'none'},{kind:'WAIT',durationTicks:5,sub:'bagworm'}]}],fixtureContent),events=result.frames.flatMap(f=>f.teamEvents.A).filter(e=>['RADAR_DETECT','CONTACT_LOST','VISUAL_DETECT'].includes(e.kind));expect(events.map(e=>e.kind)).toEqual(['RADAR_DETECT','CONTACT_LOST','VISUAL_DETECT']);expect(events.every(e=>e.targetId?.startsWith('contact-A-'))).toBe(true);expect(JSON.stringify(events)).not.toContain(b.id);expect(events.every(e=>!e.details&&!e.from&&!e.to)).toBe(true);expect(result.frames.flatMap(f=>f.teamEvents.B).filter(e=>['RADAR_DETECT','CONTACT_LOST','VISUAL_DETECT'].includes(e.kind)).every(e=>e.targetId?.startsWith('contact-B-'))).toBe(true);});
});
describe('rosters count identities and actual changes',()=>{
  it('rejects preset aliases of the same character and help chosen as base',()=>{const c=structuredClone(fixtureContent);c.characters.push({...c.characters[0]!,id:'p1-alias'});expect(validateRoster({...fixtureRoster,base:['p1','p1-alias','p3','p4']},'I',c).errors).toContain('DUPLICATE_CHARACTER');expect(validateRoster({...fixtureRoster,base:['help','p2','p3','p4']},'I',c).errors).toContain('HELP_AS_BASE:help');});
  it('allows listed no-op changes without consuming the changed-unit allowance',()=>{const changes=[0,1,2].map(unitIndex=>({unitIndex,loadout:structuredClone(fixtureContent.characters[0]!.defaultLoadout)}));expect(validateRoster({...fixtureRoster,changes},'I',fixtureContent).ok).toBe(true);changes.forEach(c=>c.loadout.main=['blade','none','meteor','ibis']);expect(validateRoster({...fixtureRoster,changes},'I',fixtureContent).errors).toContain('CHANGE_LIMIT');});
});
